# Generated by Django 5.2.17 on 2026-09-04 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorialKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('month', models.DateField(help_text='First day of the month.', unique=True, verbose_name='month')),
                ('submissions_received', models.PositiveIntegerField(default=0, verbose_name='submissions received')),
                ('desk_rejected', models.PositiveIntegerField(default=0, verbose_name='desk rejected')),
                ('sent_to_review', models.PositiveIntegerField(default=0, verbose_name='sent to review')),
                ('accepted', models.PositiveIntegerField(default=0, verbose_name='accepted')),
                ('rejected', models.PositiveIntegerField(default=0, verbose_name='rejected')),
                ('published', models.PositiveIntegerField(default=0, verbose_name='published')),
                ('acceptance_rate', models.FloatField(blank=True, null=True, verbose_name='acceptance rate (%)')),
                ('median_days_to_first_decision', models.FloatField(blank=True, null=True, verbose_name='median days to first decision')),
                ('median_review_days', models.FloatField(blank=True, null=True, verbose_name='median review days')),
                ('active_reviewers', models.PositiveIntegerField(default=0, verbose_name='active reviewers')),
                ('author_countries', models.JSONField(blank=True, default=dict, verbose_name='author countries')),
            ],
            options={
                'verbose_name': 'editorial KPI',
                'verbose_name_plural': 'editorial KPIs',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('view', 'View'), ('download', 'Download')], db_index=True, max_length=16, verbose_name='kind')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='occurred at')),
                ('ip_hash', models.CharField(db_index=True, max_length=64, verbose_name='IP hash')),
                ('user_agent_hash', models.CharField(blank=True, max_length=64, verbose_name='user agent hash')),
                ('session_key_hash', models.CharField(blank=True, max_length=64, verbose_name='session hash')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('is_bot', models.BooleanField(db_index=True, default=False, verbose_name='bot')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_events', to='journal.article', verbose_name='article')),
                ('galley', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_events', to='journal.galley', verbose_name='galley')),
            ],
            options={
                'verbose_name': 'access event',
                'verbose_name_plural': 'access events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['article', 'kind', '-occurred_at'], name='metrics_acc_article_9011c8_idx'), models.Index(fields=['ip_hash', 'article', 'kind', '-occurred_at'], name='metrics_acc_ip_hash_491487_idx')],
            },
        ),
        migrations.CreateModel(
            name='DailyArticleStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='views')),
                ('downloads', models.PositiveIntegerField(default=0, verbose_name='downloads')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='journal.article', verbose_name='article')),
            ],
            options={
                'verbose_name': 'daily article statistic',
                'verbose_name_plural': 'daily article statistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'article'], name='metrics_dai_date_b27c80_idx')],
                'constraints': [models.UniqueConstraint(fields=('article', 'date'), name='unique_daily_article_stat')],
            },
        ),
    ]
