# Generated by Django 5.2.17 on 2026-09-04 17:54

import apps.accounts.models
import django.utils.timezone
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('orcid', models.CharField(blank=True, db_index=True, max_length=19, verbose_name='ORCID iD')),
                ('orcid_verified', models.BooleanField(default=False, verbose_name='ORCID verified')),
                ('affiliation', models.CharField(blank=True, max_length=255, verbose_name='affiliation')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='department')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='city')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='country')),
                ('academic_degree', models.CharField(blank=True, max_length=128, verbose_name='academic degree')),
                ('academic_title', models.CharField(blank=True, max_length=128, verbose_name='academic title')),
                ('bio', models.TextField(blank=True, verbose_name='biography')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('scopus_author_id', models.CharField(blank=True, max_length=32, verbose_name='Scopus Author ID')),
                ('expertise', models.TextField(blank=True, help_text='Comma-separated keywords used by the reviewer finder.', verbose_name='areas of expertise')),
                ('reviews_completed', models.PositiveIntegerField(default=0, verbose_name='reviews completed')),
                ('reviews_declined', models.PositiveIntegerField(default=0, verbose_name='reviews declined')),
                ('average_review_days', models.FloatField(blank=True, null=True, verbose_name='average review days')),
                ('average_quality_rating', models.FloatField(blank=True, null=True, verbose_name='average quality rating')),
                ('accepts_review_invitations', models.BooleanField(default=True, verbose_name='accepts review invitations')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='given name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='family name')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('uz', 'Oʻzbekcha'), ('uz-cyrl', 'Ўзбекча'), ('ru', 'Русский')], default='en', max_length=10, verbose_name='preferred language')),
                ('is_reviewer', models.BooleanField(default=False, help_text='Flagged by an editor; controls appearance in the reviewer finder.', verbose_name='available as reviewer')),
                ('must_enroll_2fa', models.BooleanField(default=False, help_text='Set for staff accounts created by seeding or by an administrator.', verbose_name='must enrol in 2FA')),
                ('last_activity_at', models.DateTimeField(blank=True, null=True, verbose_name='last activity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['last_name', 'first_name', 'email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
