# Generated by Django 5.2.17 on 2026-09-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jel_codes',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='journal.jelcode', verbose_name='JEL codes'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_reviewer'], name='accounts_us_is_revi_648c53_idx'),
        ),
    ]
