# Generated by Django 5.2.17 on 2026-09-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='editor_in_chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='journal.editorialboardmember', verbose_name='editor-in-chief'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='indexing_badges',
            field=models.ManyToManyField(blank=True, to='core.indexingservice', verbose_name='indexing services'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['menu_group', 'menu_order'], name='core_page_menu_gr_4aa81f_idx'),
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['is_published'], name='core_page_is_publ_f1d499_idx'),
        ),
    ]
