# Generated by Django 5.2.17 on 2026-09-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='journal_name',
            field=models.CharField(default='MEZON: Review of Economic Research', max_length=255, verbose_name='journal name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='journal_name_en',
            field=models.CharField(default='MEZON: Review of Economic Research', max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='journal_name_ru',
            field=models.CharField(default='MEZON: Review of Economic Research', max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='journal_name_uz',
            field=models.CharField(default='MEZON: Review of Economic Research', max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='journal_name_uz_cyrl',
            field=models.CharField(default='MEZON: Review of Economic Research', max_length=255, null=True, verbose_name='journal name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='short_code',
            field=models.CharField(default='MRER', max_length=16, verbose_name='short code'),
        ),
    ]
