# Generated by Django 5.2.17 on 2026-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mezon_leftovers'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='print_info_page',
            field=models.TextField(blank=True, help_text='Optional page after the editorial board in every issue PDF, e.g. the list of accredited specialities. One item per line; a line starting with # is a heading.', verbose_name='issue PDF information page'),
        ),
    ]
