# Generated by Django 5.2.17 on 2026-09-17 12:51

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_print_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='print_back_cover_background',
            field=models.ImageField(blank=True, help_text='Full-page picture behind the back cover. Leave empty for the built-in artwork.', null=True, upload_to=apps.core.models.print_asset_upload_to, verbose_name='issue PDF back cover background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='print_cover_background',
            field=models.ImageField(blank=True, help_text='Full-page picture behind the generated cover (A4 portrait, at least 1240×1754 px). It is darkened so the title stays readable. Leave empty for the built-in artwork.', null=True, upload_to=apps.core.models.print_asset_upload_to, verbose_name='issue PDF cover background'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='print_page_background',
            field=models.ImageField(blank=True, help_text='Light full-page picture (frame, watermark) behind the editorial board, contents and article pages. Keep it pale: the text is printed on top.', null=True, upload_to=apps.core.models.print_asset_upload_to, verbose_name='issue PDF page background'),
        ),
    ]
