# Generated by Django 5.2.17 on 2026-09-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_print_backgrounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='publisher_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='publisher_name_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='publisher_name_ru',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='publisher_name_uz',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='publisher_name_uz_cyrl',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='publisher'),
        ),
    ]
