# Generated by Django 5.2.17 on 2026-09-04 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('journal', '0001_initial'),
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='submission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_article', to='submissions.submission', verbose_name='submission'),
        ),
        migrations.AddField(
            model_name='articlestatisticsnapshot',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='journal.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='author',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='journal.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorships', to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_memberships', to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
        migrations.AddField(
            model_name='galley',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleys', to='journal.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='article',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.issue', verbose_name='issue'),
        ),
        migrations.AddField(
            model_name='jelcode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='journal.jelcode', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='article',
            name='jel_codes',
            field=models.ManyToManyField(blank=True, related_name='articles', to='journal.jelcode', verbose_name='JEL codes'),
        ),
        migrations.AddIndex(
            model_name='keyword',
            index=models.Index(fields=['slug'], name='journal_key_slug_df4499_idx'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='articles', to='journal.keyword', verbose_name='keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.license', verbose_name='licence'),
        ),
        migrations.AddField(
            model_name='reference',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='journal.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='section',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='edited_sections', to=settings.AUTH_USER_MODEL, verbose_name='section editors'),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='board_members', to='journal.section', verbose_name='sections'),
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='journal.section', verbose_name='section'),
        ),
        migrations.AddField(
            model_name='issue',
            name='volume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='journal.volume', verbose_name='volume'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['family_name', 'given_name'], name='journal_aut_family__9a14b8_idx'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['orcid'], name='journal_aut_orcid_a83965_idx'),
        ),
        migrations.AddIndex(
            model_name='galley',
            index=models.Index(fields=['article', 'is_primary'], name='journal_gal_article_d9b6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='jelcode',
            index=models.Index(fields=['level', 'code'], name='journal_jel_level_c4b013_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['order'], name='journal_sec_order_9ceac2_idx'),
        ),
        migrations.AddIndex(
            model_name='editorialboardmember',
            index=models.Index(fields=['role', 'order'], name='journal_edi_role_6fe9e0_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='journal_art_status_00aaa9_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['issue', 'article_number'], name='journal_art_issue_i_4a6926_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['section', '-published_at'], name='journal_art_section_2c8d85_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['doi'], name='journal_art_doi_f82e66_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_published', '-published_at'], name='journal_iss_is_publ_f74b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_current'], name='journal_iss_is_curr_6a56fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('volume', 'number'), name='unique_issue_per_volume'),
        ),
    ]
