# Generated by Django 5.2.17 on 2026-09-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galley',
            name='label',
            field=models.CharField(choices=[('PDF', 'PDF'), ('PDF-UZ', 'PDF (Uzbek)'), ('PDF-RU', 'PDF (Russian)'), ('HTML', 'Full text (HTML)'), ('XML', 'JATS XML'), ('SUPP', 'Supplementary')], default='PDF', max_length=16, verbose_name='label'),
        ),
    ]
