# Generated by Django 5.2.17 on 2026-09-12 02:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_galley_html'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True, verbose_name='search vector'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='journal_article_search_gin'),
        ),
    ]
