# Generated by Django 5.2.17 on 2026-09-17 12:02

import apps.journal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_populate_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='offprint_pdf',
            field=models.FileField(blank=True, help_text='The article in the journal layout, built with the issue PDF.', null=True, upload_to=apps.journal.models.galley_upload_to, verbose_name='offprint PDF'),
        ),
        migrations.AddField(
            model_name='article',
            name='offprint_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='offprint sent to authors'),
        ),
        migrations.AddField(
            model_name='issue',
            name='print_built_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='layout built at'),
        ),
        migrations.AddField(
            model_name='issue',
            name='print_error',
            field=models.TextField(blank=True, verbose_name='layout error'),
        ),
        migrations.AddField(
            model_name='issue',
            name='print_first_page',
            field=models.PositiveIntegerField(default=1, help_text='Page number of the cover; raise it to continue the pagination of a previous part.', verbose_name='first page number'),
        ),
        migrations.AddField(
            model_name='issue',
            name='print_language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Oʻzbekcha'), ('uz-cyrl', 'Ўзбекча'), ('ru', 'Русский')], default='uz', max_length=10, verbose_name='print language'),
        ),
        migrations.AddField(
            model_name='issue',
            name='print_page_count',
            field=models.PositiveIntegerField(default=0, verbose_name='pages in the issue PDF'),
        ),
        migrations.AddField(
            model_name='issue',
            name='print_status',
            field=models.CharField(choices=[('none', 'not built'), ('queued', 'queued'), ('building', 'building'), ('ready', 'ready'), ('failed', 'failed')], default='none', max_length=16, verbose_name='layout status'),
        ),
    ]
