"""Demonstration articles: plausible economics papers with trilingual metadata.

Every entry carries a title, abstract and keywords in English, Uzbek Latin and
Russian (Uzbek Cyrillic is generated by transliteration), two or three authors
from at least four countries, JEL codes and statements.  References are built
by :func:`build_references` from a deterministic pool so that each article has
20–35 entries with realistic DOI patterns; they are clearly example data.
"""

from __future__ import annotations

import random
from typing import Any

# ---------------------------------------------------------------------------
# Reference generator
# ---------------------------------------------------------------------------
_REF_AUTHORS = [
    "Acemoglu, D., & Robinson, J. A.", "Aghion, P., & Howitt, P.", "Alesina, A., & Perotti, R.",
    "Autor, D. H.", "Banerjee, A. V., & Duflo, E.", "Bernanke, B. S., & Gertler, M.",
    "Besley, T., & Persson, T.", "Blanchard, O., & Leigh, D.", "Brunnermeier, M. K.",
    "Calvo, G. A.", "Card, D., & Krueger, A. B.", "Chetty, R., & Hendren, N.",
    "Dell, M., & Olken, B. A.", "Djankov, S., & Ramalho, R.", "Eichengreen, B.",
    "Fernández-Villaverde, J.", "Frankel, J. A., & Romer, D.", "Gopinath, G., & Itskhoki, O.",
    "Hall, R. E., & Jones, C. I.", "Head, K., & Mayer, T.", "Hsieh, C.-T., & Klenow, P. J.",
    "Imbens, G. W., & Wooldridge, J. M.", "Jorda, O., & Taylor, A. M.", "Kaplan, G., & Violante, G. L.",
    "Krugman, P.", "La Porta, R., & Shleifer, A.", "Levchenko, A. A.", "Melitz, M. J.",
    "Mian, A., & Sufi, A.", "Nakamura, E., & Steinsson, J.", "Obstfeld, M., & Rogoff, K.",
    "Piketty, T., & Saez, E.", "Rajan, R. G., & Zingales, L.", "Reinhart, C. M., & Rogoff, K. S.",
    "Rodrik, D.", "Romer, P. M.", "Sachs, J. D.", "Shleifer, A., & Vishny, R. W.",
    "Stiglitz, J. E.", "Syverson, C.", "Tirole, J.", "Wooldridge, J. M.",
    "Yusupova, D., & Karimov, S.", "Ismoilov, R., & Nazarova, G.", "Tulaganov, A.",
    "Sultanov, B., & Ergashev, D.",
]

_REF_TITLES = [
    "Institutions as a fundamental cause of long-run growth",
    "Trade liberalisation and firm productivity: evidence from a natural experiment",
    "The macroeconomic effects of tax administration reform",
    "Financial development, credit constraints and misallocation",
    "Digital payments and tax compliance in emerging economies",
    "Exchange rate pass-through in small open economies",
    "Public investment multipliers in developing countries",
    "Labour market frictions and the returns to schooling",
    "Regional convergence and the geography of firm entry",
    "Measuring the informal economy: a review of methods",
    "Value chains, upgrading and the productivity of exporters",
    "Bank competition and the cost of credit for small firms",
    "The distributional consequences of energy subsidy reform",
    "Agricultural water pricing and allocative efficiency",
    "Remittances, consumption smoothing and household investment",
    "The effect of customs digitalisation on trade costs",
    "Monetary policy transmission under partial dollarisation",
    "Fiscal rules and the cyclicality of public spending",
    "Firm dynamics and job creation in transition economies",
    "Innovation policy and the allocation of research subsidies",
    "Human capital, migration and the brain drain debate",
    "Sovereign debt sustainability in commodity exporters",
    "Estimating the elasticity of taxable income",
    "Corporate governance and investment efficiency",
    "Machine learning methods for policy evaluation",
    "Inflation expectations and central bank communication",
    "Trade facilitation agreements and export diversification",
    "Financial inclusion and small business growth",
    "Structural transformation and sectoral productivity gaps",
    "Land reform, tenure security and agricultural investment",
    "Green transition policies and industrial competitiveness",
    "The economics of state-owned enterprise reform",
    "Public procurement transparency and firm participation",
    "Educational attainment and intergenerational mobility",
    "Infrastructure quality and regional income disparities",
]

_REF_JOURNALS = [
    ("American Economic Review", "10.1257"),
    ("Journal of Economic Growth", "10.1007"),
    ("Quarterly Journal of Economics", "10.1093"),
    ("Journal of Development Economics", "10.1016"),
    ("Journal of International Economics", "10.1016"),
    ("Review of Economics and Statistics", "10.1162"),
    ("Economic Journal", "10.1093"),
    ("Journal of Public Economics", "10.1016"),
    ("World Development", "10.1016"),
    ("Journal of Comparative Economics", "10.1016"),
    ("China Economic Review", "10.1016"),
    ("Economics of Transition and Institutional Change", "10.1111"),
    ("Energy Economics", "10.1016"),
    ("Journal of Banking & Finance", "10.1016"),
    ("Economic Modelling", "10.1016"),
    ("Emerging Markets Review", "10.1016"),
    ("Post-Communist Economies", "10.1080"),
    ("Central Asian Journal of Economics", "10.1080"),
]


def build_references(seed_value: int, count: int) -> list[str]:
    """Build ``count`` deterministic, realistic-looking APA 7 references.

    The DOIs use the real registrant prefixes of the journals named, but the
    suffixes are invented; the seed command marks the whole set as example data.
    """
    rng = random.Random(seed_value)
    references: list[str] = []
    used: set[tuple[int, int]] = set()
    for index in range(count):
        while True:
            author_index = rng.randrange(len(_REF_AUTHORS))
            title_index = rng.randrange(len(_REF_TITLES))
            if (author_index, title_index) not in used:
                used.add((author_index, title_index))
                break
        journal, prefix = rng.choice(_REF_JOURNALS)
        year = rng.randint(2009, 2025)
        volume = rng.randint(8, 140)
        issue = rng.randint(1, 6)
        first_page = rng.randint(1, 900)
        last_page = first_page + rng.randint(12, 40)
        doi = f"{prefix}/example.{year}.{rng.randint(1000, 9999)}"
        references.append(
            f"{_REF_AUTHORS[author_index]} ({year}). {_REF_TITLES[title_index]}. "
            f"*{journal}*, {volume}({issue}), {first_page}–{last_page}. "
            f"https://doi.org/{doi}"
        )
    return references


# ---------------------------------------------------------------------------
# Articles
# ---------------------------------------------------------------------------
#: issue_index: 0, 1, 2 = Vol. 1 issues 1–3; None = Online First.
ARTICLES: list[dict[str, Any]] = [
    {
        "section": "public-finance-taxation-customs",
        "issue": 0,
        "jel": ["H26", "F13", "O33"],
        "title": {
            "en": "Customs Digitalisation and Trade Facilitation in Central Asia: Evidence from Firm-Level Data",
            "uz": "Markaziy Osiyoda bojxona raqamlashuvi va savdoni soddalashtirish: korxona darajasidagi maʼlumotlar asosida",
            "ru": "Цифровизация таможни и упрощение торговли в Центральной Азии: данные на уровне фирм",
        },
        "abstract": {
            "en": "Customs administrations across Central Asia have replaced paper declarations with electronic single-window systems, but the effect of that change on firms has not been measured with disaggregated data. This paper exploits the staggered roll-out of an electronic declaration system across border posts in Uzbekistan between 2019 and 2023, combined with the universe of customs declarations covering 18,400 exporting and importing firms, to estimate the causal effect of digitalisation on clearance time and trade volumes. Using a staggered difference-in-differences estimator robust to heterogeneous treatment effects, we find that digitalisation reduced median clearance time by 31 per cent and raised the value of imports by 6.8 per cent within two years. Effects are three times larger for small firms and for firms with no prior customs brokerage relationship, which is consistent with digitalisation lowering fixed compliance costs rather than variable ones. We find no effect on tariff revenue per declaration, suggesting the gains came from time savings rather than from changes in valuation. The results indicate that procedural reform can raise trade volumes without tariff liberalisation.",
            "uz": "Markaziy Osiyo bojxona idoralari qogʻoz deklaratsiyalarni elektron «yagona darcha» tizimlari bilan almashtirdi, ammo bu oʻzgarishning korxonalarga taʼsiri batafsil maʼlumotlar asosida oʻlchanmagan. Ushbu maqolada 2019–2023-yillarda Oʻzbekiston bojxona postlarida elektron deklaratsiya tizimining bosqichma-bosqich joriy etilishi va 18 400 eksportchi hamda importchi korxonani qamrab olgan barcha bojxona deklaratsiyalari maʼlumotlaridan foydalanib, raqamlashuvning rasmiylashtirish vaqti va savdo hajmiga sababiy taʼsiri baholanadi. Turlicha taʼsirlarga chidamli bosqichli farqlar-farqi baholovchisidan foydalanib, raqamlashuv rasmiylashtirishning median vaqtini 31 foizga qisqartirgani va ikki yil ichida import qiymatini 6,8 foizga oshirgani aniqlandi. Taʼsir kichik korxonalar va ilgari bojxona brokeri bilan ishlamagan korxonalarda uch baravar kuchli, bu esa raqamlashuv oʻzgaruvchan emas, doimiy rioya xarajatlarini kamaytirishini koʻrsatadi. Deklaratsiyaga toʻgʻri keladigan boj tushumiga taʼsir topilmadi — demak, yutuq baholashning oʻzgarishidan emas, vaqt tejashdan kelgan. Natijalar protsessual islohot tarif liberallashuvisiz ham savdo hajmini oshira olishini koʻrsatadi.",
            "ru": "Таможенные администрации Центральной Азии заменили бумажные декларации электронными системами «единого окна», однако влияние этой перемены на фирмы не измерялось на дезагрегированных данных. В статье используется поэтапное внедрение системы электронного декларирования на таможенных постах Узбекистана в 2019–2023 годах вместе с полным массивом таможенных деклараций, охватывающим 18 400 экспортирующих и импортирующих фирм, для оценки причинного эффекта цифровизации на время оформления и объёмы торговли. С помощью поэтапной оценки «разность разностей», устойчивой к гетерогенным эффектам, мы обнаруживаем, что цифровизация сократила медианное время оформления на 31 процент и увеличила стоимость импорта на 6,8 процента за два года. Эффект втрое сильнее для малых фирм и для фирм, ранее не работавших с таможенными брокерами, что согласуется с гипотезой о снижении постоянных, а не переменных издержек соблюдения требований. Влияния на таможенные поступления в расчёте на декларацию не обнаружено, что указывает на выигрыш от экономии времени, а не от изменений в оценке стоимости. Результаты показывают, что процедурная реформа способна увеличить объёмы торговли без тарифной либерализации.",
        },
        "keywords": {
            "en": ["customs administration", "trade facilitation", "digitalisation", "firm-level data", "Central Asia", "difference-in-differences"],
            "uz": ["bojxona maʼmuriyati", "savdoni soddalashtirish", "raqamlashuv", "korxona darajasidagi maʼlumotlar", "Markaziy Osiyo", "farqlar farqi"],
            "ru": ["таможенное администрирование", "упрощение торговли", "цифровизация", "данные на уровне фирм", "Центральная Азия", "разность разностей"],
        },
        "authors": [
            {"given": "Dilnoza", "family": "Yusupova", "affiliation": {"en": "Institute of Forecasting and Macroeconomic Research", "uz": "Prognozlashtirish va makroiqtisodiy tadqiqotlar instituti", "ru": "Институт прогнозирования и макроэкономических исследований"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0011", "corresponding": True, "credit": ["Conceptualization", "Formal analysis", "Writing – original draft"]},
            {"given": "Aidos", "family": "Nurgaliyev", "affiliation": {"en": "Graduate School of Economics", "uz": "Iqtisodiyot oliy maktabi", "ru": "Высшая школа экономики"}, "city": "Almaty", "country": "KZ", "orcid": "0000-0002-1000-0012", "credit": ["Data curation", "Methodology"]},
            {"given": "Marta", "family": "Kowalska", "affiliation": {"en": "Warsaw School of Economics", "uz": "Varshava iqtisodiyot maktabi", "ru": "Варшавская школа экономики"}, "city": "Warsaw", "country": "PL", "orcid": "0000-0002-1000-0013", "credit": ["Writing – review & editing", "Supervision"]},
        ],
    },
    {
        "section": "macroeconomics-monetary-fiscal-policy",
        "issue": 0,
        "jel": ["E52", "E31", "F31"],
        "title": {
            "en": "Exchange Rate Pass-Through under Partial Dollarisation: Evidence from a Managed Float",
            "uz": "Qisman dollarlashuv sharoitida valyuta kursining oʻtishi: boshqariladigan suzuvchi kurs misolida",
            "ru": "Перенос валютного курса в условиях частичной долларизации: опыт управляемого плавания",
        },
        "abstract": {
            "en": "How much of a depreciation reaches consumer prices when a large share of deposits and loans is denominated in foreign currency? We estimate exchange rate pass-through for an economy that moved from a fixed to a managed float regime while deposit dollarisation stood near 40 per cent. Using monthly disaggregated price indices for 312 product groups from 2016 to 2024 and local projections with an external instrument built from commodity price shocks, we estimate a cumulative twelve-month pass-through of 0.34 for the overall consumer price index, rising to 0.61 for tradable goods and falling to 0.09 for services. Pass-through is markedly asymmetric: depreciations transmit almost twice as strongly as appreciations of the same magnitude. Dollarisation amplifies the response of durable goods prices but not of food. A counterfactual exercise suggests that reducing deposit dollarisation to 20 per cent would lower headline pass-through by about a quarter. The findings imply that de-dollarisation policy and inflation targeting are complements rather than substitutes.",
            "uz": "Depozit va kreditlarning katta qismi chet el valyutasida boʻlganda devalvatsiyaning qanchasi isteʼmol narxlariga yetib boradi? Biz depozitlar dollarlashuvi 40 foizga yaqin boʻlgan sharoitda qatʼiy kursdan boshqariladigan suzuvchi kursga oʻtgan iqtisodiyot uchun valyuta kursining oʻtish darajasini baholaymiz. 2016–2024-yillar uchun 312 ta mahsulot guruhi boʻyicha oylik detallashtirilgan narx indekslari va xomashyo narxi zarbalaridan qurilgan tashqi instrument bilan lokal proyeksiyalardan foydalanib, umumiy isteʼmol narxlari indeksi uchun oʻn ikki oylik jamlangan oʻtish darajasi 0,34 ni, savdo qilinadigan tovarlar uchun 0,61 ni va xizmatlar uchun 0,09 ni tashkil etishini aniqladik. Oʻtish sezilarli darajada assimetrik: devalvatsiya bir xil hajmdagi revalvatsiyaga qaraganda deyarli ikki barobar kuchliroq uzatiladi. Dollarlashuv uzoq muddat foydalaniladigan tovarlar narxining javobini kuchaytiradi, oziq-ovqatnikini esa yoʻq. Kontrfaktual hisob depozit dollarlashuvini 20 foizgacha kamaytirish umumiy oʻtish darajasini chorak qismga pasaytirishini koʻrsatadi. Natijalar dedollarlashtirish siyosati va inflyatsiyani nishonlash bir-birini almashtirmasligini, toʻldirishini bildiradi.",
            "ru": "Какая часть девальвации доходит до потребительских цен, когда значительная доля депозитов и кредитов номинирована в иностранной валюте? Мы оцениваем перенос валютного курса для экономики, перешедшей от фиксированного курса к управляемому плаванию при долларизации депозитов около 40 процентов. Используя месячные дезагрегированные индексы цен по 312 товарным группам за 2016–2024 годы и локальные проекции с внешним инструментом, построенным на шоках сырьевых цен, мы получаем кумулятивный двенадцатимесячный перенос 0,34 для общего индекса потребительских цен, 0,61 для торгуемых товаров и 0,09 для услуг. Перенос заметно асимметричен: девальвация передаётся почти вдвое сильнее, чем ревальвация той же величины. Долларизация усиливает реакцию цен товаров длительного пользования, но не продовольствия. Контрфактический расчёт показывает, что снижение долларизации депозитов до 20 процентов уменьшило бы совокупный перенос примерно на четверть. Выводы означают, что политика дедолларизации и инфляционное таргетирование дополняют, а не заменяют друг друга.",
        },
        "keywords": {
            "en": ["exchange rate pass-through", "dollarisation", "inflation", "monetary policy", "local projections", "managed float"],
            "uz": ["valyuta kursi oʻtishi", "dollarlashuv", "inflyatsiya", "pul-kredit siyosati", "lokal proyeksiyalar", "boshqariladigan suzuvchi kurs"],
            "ru": ["перенос валютного курса", "долларизация", "инфляция", "денежно-кредитная политика", "локальные проекции", "управляемое плавание"],
        },
        "authors": [
            {"given": "Timur", "family": "Abdullayev", "affiliation": {"en": "University of Economics and Finance", "uz": "Iqtisodiyot va moliya universiteti", "ru": "Университет экономики и финансов"}, "city": "Samarkand", "country": "UZ", "orcid": "0000-0002-1000-0021", "corresponding": True, "credit": ["Conceptualization", "Formal analysis"]},
            {"given": "Ayşe", "family": "Demir", "affiliation": {"en": "Middle East Technical University", "uz": "Yaqin Sharq texnika universiteti", "ru": "Ближневосточный технический университет"}, "city": "Ankara", "country": "TR", "orcid": "0000-0002-1000-0022", "credit": ["Methodology", "Writing – review & editing"]},
        ],
    },
    {
        "section": "finance-banking-investment",
        "issue": 0,
        "jel": ["G21", "G28", "L26"],
        "title": {
            "en": "Bank Competition and the Cost of Credit for Small Firms in Transition Economies",
            "uz": "Oʻtish davri iqtisodiyotlarida bank raqobati va kichik korxonalar uchun kredit narxi",
            "ru": "Банковская конкуренция и стоимость кредита для малых фирм в переходных экономиках",
        },
        "abstract": {
            "en": "Consolidation in transition banking systems has raised concentration, yet the consequences for small borrowers remain contested. We assemble a panel of 1,240 banks and 96,000 small-firm loan contracts from eleven transition economies between 2012 and 2023 and estimate the effect of local market concentration on loan pricing, collateral requirements and rejection rates. Identification exploits mergers between banks with no overlapping branch network in a given district, which change local concentration for reasons unrelated to local demand. A ten-point increase in the district Herfindahl index raises the spread charged to small firms by 42 basis points and the required collateral ratio by 7 percentage points, but leaves the rejection rate unchanged. The pricing effect is concentrated among first-time borrowers and disappears for firms with three or more years of relationship history, which is consistent with information rents rather than market power over creditworthy incumbents. State-owned banks show no concentration effect, but charge higher spreads on average. We discuss the implications for competition policy and for credit registry design.",
            "uz": "Oʻtish davri bank tizimlarida konsolidatsiya konsentratsiyani oshirdi, ammo kichik qarz oluvchilar uchun oqibatlari bahsli. Biz 2012–2023-yillarda oʻn bitta oʻtish davri iqtisodiyotidan 1 240 ta bank va 96 000 ta kichik korxona kredit shartnomasidan iborat panel toʻpladik va mahalliy bozor konsentratsiyasining kredit narxi, garov talablari hamda rad etish darajasiga taʼsirini baholadik. Identifikatsiya muayyan tumanda filiallar tarmogʻi kesishmaydigan banklar qoʻshilishiga asoslanadi — bunday qoʻshilish mahalliy talabdan mustaqil ravishda konsentratsiyani oʻzgartiradi. Tuman Herfindal indeksining oʻn punktga oshishi kichik korxonalar uchun spredni 42 bazis punktga, talab qilinadigan garov nisbatini 7 foiz punktga oshiradi, rad etish darajasini esa oʻzgartirmaydi. Narx taʼsiri birinchi marta kredit olayotgan korxonalarda toʻplangan va uch yildan ortiq munosabat tarixiga ega korxonalarda yoʻqoladi — bu bozor kuchidan koʻra axborot rentasiga mos keladi. Davlat banklarida konsentratsiya taʼsiri koʻrinmaydi, ammo oʻrtacha spred yuqoriroq. Raqobat siyosati va kredit reyestri dizayni uchun xulosalar muhokama qilinadi.",
            "ru": "Консолидация банковских систем переходных экономик повысила концентрацию, однако последствия для малых заёмщиков остаются спорными. Мы собрали панель из 1 240 банков и 96 000 кредитных договоров малых фирм по одиннадцати переходным экономикам за 2012–2023 годы и оценили влияние локальной концентрации на стоимость кредита, требования к залогу и долю отказов. Идентификация опирается на слияния банков, филиальные сети которых в данном районе не пересекались, что меняет локальную концентрацию по причинам, не связанным с местным спросом. Рост районного индекса Херфиндаля на десять пунктов увеличивает спред для малых фирм на 42 базисных пункта и требуемое залоговое покрытие на 7 процентных пунктов, но не меняет долю отказов. Ценовой эффект сосредоточен среди заёмщиков-новичков и исчезает для фирм с историей отношений более трёх лет, что согласуется с информационной рентой, а не с рыночной властью над надёжными клиентами. У государственных банков эффект концентрации отсутствует, но средний спред выше. Обсуждаются выводы для политики конкуренции и устройства кредитного реестра.",
        },
        "keywords": {
            "en": ["bank competition", "small business lending", "credit spreads", "collateral", "transition economies", "market concentration"],
            "uz": ["bank raqobati", "kichik biznes kreditlash", "kredit spredlari", "garov", "oʻtish davri iqtisodiyoti", "bozor konsentratsiyasi"],
            "ru": ["банковская конкуренция", "кредитование малого бизнеса", "кредитные спреды", "залог", "переходные экономики", "рыночная концентрация"],
        },
        "authors": [
            {"given": "Aziz", "family": "Karimov", "affiliation": {"en": "Banking and Finance Academy", "uz": "Bank-moliya akademiyasi", "ru": "Банковско-финансовая академия"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0031", "corresponding": True, "credit": ["Conceptualization", "Data curation", "Formal analysis"]},
            {"given": "Elena", "family": "Sokolova", "affiliation": {"en": "Graduate School of Economics", "uz": "Iqtisodiyot oliy maktabi", "ru": "Высшая школа экономики"}, "city": "Almaty", "country": "KZ", "orcid": "0000-0002-1000-0032", "credit": ["Methodology", "Validation"]},
        ],
    },
    {
        "section": "regional-sectoral-development",
        "issue": 0,
        "jel": ["Q25", "Q18", "R58"],
        "title": {
            "en": "Water Pricing and Allocative Efficiency in Irrigated Agriculture: A Structural Estimation",
            "uz": "Sugʻoriladigan dehqonchilikda suv narxi va taqsimlash samaradorligi: strukturaviy baholash",
            "ru": "Цена воды и эффективность распределения в орошаемом земледелии: структурная оценка",
        },
        "abstract": {
            "en": "Irrigation water in much of Central Asia is allocated administratively at prices far below its opportunity cost, and reform proposals are contested because the efficiency gains are unmeasured. We estimate a structural model of farm water demand using plot-level data on 4,700 farms across three river basins, combined with satellite-derived evapotranspiration measures that let us observe water use independently of self-reports. Estimated marginal products of water differ by a factor of 4.3 between the tenth and ninetieth percentile of farms within the same district, indicating substantial misallocation. Simulating a volumetric tariff set at the estimated shadow price, we find aggregate agricultural output rises by 11 per cent with 19 per cent less water applied, but that the gains are concentrated among larger farms and that the smallest quintile would lose income without compensating transfers. A two-part tariff with a free basic allocation preserves most of the efficiency gain while leaving the income distribution unchanged. The results argue for pricing reform combined with an explicit distributional instrument.",
            "uz": "Markaziy Osiyoning katta qismida sugʻorish suvi maʼmuriy tarzda, muqobil qiymatidan ancha past narxda taqsimlanadi va islohot takliflari bahsli, chunki samaradorlik yutugʻi oʻlchanmagan. Biz uchta daryo havzasidagi 4 700 fermer xoʻjaligi boʻyicha uchastka darajasidagi maʼlumotlar va sunʼiy yoʻldoshdan olingan evapotranspiratsiya oʻlchovlaridan foydalanib, suvga talabning strukturaviy modelini baholadik; sunʼiy yoʻldosh maʼlumotlari suv sarfini fermerlar hisobotidan mustaqil kuzatish imkonini beradi. Bir tumandagi xoʻjaliklarning oʻninchi va toʻqsoninchi protsentili orasida suvning chegaraviy mahsuldorligi 4,3 barobar farq qiladi — bu jiddiy notoʻgʻri taqsimotni koʻrsatadi. Baholangan soya narxi darajasidagi hajmiy tarifni modellashtirganda, jami qishloq xoʻjaligi mahsuloti 11 foizga oshib, suv sarfi 19 foizga kamayishi aniqlandi; ammo yutuq yirik xoʻjaliklarda toʻplanadi va eng kichik kvintil kompensatsion transfertlarsiz daromadini yoʻqotadi. Bepul bazaviy hajmga ega ikki qismli tarif samaradorlik yutugʻining koʻp qismini saqlab, daromad taqsimotini oʻzgartirmaydi. Natijalar narx islohotini aniq taqsimot vositasi bilan birga oʻtkazish kerakligini koʻrsatadi.",
            "ru": "Оросительная вода на значительной части Центральной Азии распределяется административно по ценам намного ниже альтернативной стоимости, а предложения о реформе оспариваются, поскольку выигрыш в эффективности не измерен. Мы оцениваем структурную модель спроса на воду на данных уровня участков по 4 700 хозяйствам в трёх речных бассейнах вместе со спутниковыми оценками эвапотранспирации, позволяющими наблюдать водопользование независимо от самоотчётов. Оценённые предельные продукты воды различаются в 4,3 раза между десятым и девяностым перцентилем хозяйств одного района, что указывает на существенное неверное распределение. Моделируя объёмный тариф на уровне оценённой теневой цены, мы получаем рост совокупного сельскохозяйственного выпуска на 11 процентов при сокращении водопользования на 19 процентов, однако выигрыш концентрируется у крупных хозяйств, а нижний квинтиль теряет доход без компенсирующих трансфертов. Двухставочный тариф с бесплатным базовым объёмом сохраняет большую часть выигрыша в эффективности, не меняя распределения доходов. Результаты говорят в пользу ценовой реформы в сочетании с явным распределительным инструментом.",
        },
        "keywords": {
            "en": ["water pricing", "irrigation", "allocative efficiency", "structural estimation", "remote sensing", "agricultural policy"],
            "uz": ["suv narxi", "sugʻorish", "taqsimlash samaradorligi", "strukturaviy baholash", "masofadan zondlash", "agrar siyosat"],
            "ru": ["цена воды", "орошение", "эффективность распределения", "структурная оценка", "дистанционное зондирование", "аграрная политика"],
        },
        "authors": [
            {"given": "Bekzod", "family": "Toshmatov", "affiliation": {"en": "Centre for Regional Studies", "uz": "Hududiy tadqiqotlar markazi", "ru": "Центр региональных исследований"}, "city": "Bukhara", "country": "UZ", "orcid": "0000-0002-1000-0041", "corresponding": True, "credit": ["Conceptualization", "Investigation", "Formal analysis"]},
            {"given": "Michael", "family": "Brennan", "affiliation": {"en": "University of Manchester", "uz": "Manchester universiteti", "ru": "Манчестерский университет"}, "city": "Manchester", "country": "GB", "orcid": "0000-0002-1000-0042", "credit": ["Methodology", "Supervision"]},
            {"given": "Gulnora", "family": "Nazarova", "affiliation": {"en": "National University", "uz": "Milliy universitet", "ru": "Национальный университет"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0043", "credit": ["Data curation", "Visualization"]},
        ],
    },
    {
        "section": "digital-economy-innovation",
        "issue": 1,
        "jel": ["O33", "L81", "D22"],
        "title": {
            "en": "Platform Adoption and Firm Productivity: Evidence from E-Commerce Entry by Small Retailers",
            "uz": "Platformaga qoʻshilish va korxona unumdorligi: kichik chakana savdo korxonalarining elektron tijoratga kirishi misolida",
            "ru": "Присоединение к платформе и производительность фирм: выход малых розничных компаний в электронную коммерцию",
        },
        "abstract": {
            "en": "Digital marketplaces are widely promoted as a route to productivity growth for small firms, but the evidence rests mostly on self-selected adopters. We study the entry of 21,300 small retailers onto a national e-commerce platform between 2020 and 2024, using the platform's staggered expansion into new districts as an instrument for adoption. Adoption raises revenue by 23 per cent and labour productivity by 14 per cent after two years, with no detectable effect on employment. The productivity gain comes almost entirely from higher capacity utilisation rather than from price increases or from changes in the product mix. Effects are strongly heterogeneous: firms that already had electronic payment infrastructure gain three times as much as those that did not, and firms in districts with poor logistics gain nothing at all. We estimate that complementary investment in payment and delivery infrastructure accounts for more of the observed variation in gains than firm characteristics do. The findings caution against treating platform access as a stand-alone policy instrument.",
            "uz": "Raqamli bozorlar kichik korxonalar unumdorligini oshirish yoʻli sifatida keng targʻib qilinadi, ammo dalillar asosan oʻzini oʻzi tanlagan foydalanuvchilarga tayanadi. Biz 2020–2024-yillarda 21 300 ta kichik chakana savdo korxonasining milliy elektron tijorat platformasiga kirishini oʻrgandik va platformaning yangi tumanlarga bosqichma-bosqich kengayishini qoʻshilish uchun instrument sifatida ishlatdik. Qoʻshilish ikki yildan keyin tushumni 23 foizga, mehnat unumdorligini 14 foizga oshiradi, bandlikka sezilarli taʼsir koʻrsatmaydi. Unumdorlik oʻsishi deyarli butunlay quvvatdan foydalanish darajasining oshishidan kelib chiqadi, narx koʻtarilishi yoki mahsulot tarkibi oʻzgarishidan emas. Taʼsir sezilarli darajada turlicha: elektron toʻlov infratuzilmasiga ega korxonalar uch barobar koʻproq yutadi, logistikasi yomon tumanlardagi korxonalar esa umuman yutmaydi. Toʻlov va yetkazib berish infratuzilmasiga qoʻshimcha investitsiya kuzatilgan farqlarni korxona xususiyatlariga qaraganda koʻproq izohlashini baholadik. Natijalar platformaga kirishni mustaqil siyosat vositasi sifatida qarashdan ogohlantiradi.",
            "ru": "Цифровые маркетплейсы широко продвигаются как путь к росту производительности малых фирм, но доказательства опираются в основном на самоотбирающихся участников. Мы изучаем выход 21 300 малых розничных компаний на национальную платформу электронной коммерции в 2020–2024 годах, используя поэтапное расширение платформы в новые районы как инструмент для присоединения. Присоединение повышает выручку на 23 процента и производительность труда на 14 процентов через два года, не оказывая заметного влияния на занятость. Прирост производительности почти полностью обусловлен более высокой загрузкой мощностей, а не ростом цен или изменением товарного набора. Эффекты сильно неоднородны: фирмы, уже имевшие инфраструктуру электронных платежей, выигрывают втрое больше, а фирмы в районах со слабой логистикой не выигрывают вовсе. По нашим оценкам, дополнительные инвестиции в платёжную и доставочную инфраструктуру объясняют больше наблюдаемых различий, чем характеристики самих фирм. Результаты предостерегают от рассмотрения доступа к платформе как самостоятельного инструмента политики.",
        },
        "keywords": {
            "en": ["e-commerce", "platform economics", "firm productivity", "digital adoption", "small retailers", "instrumental variables"],
            "uz": ["elektron tijorat", "platforma iqtisodiyoti", "korxona unumdorligi", "raqamli qoʻshilish", "kichik chakana savdo", "instrumental oʻzgaruvchilar"],
            "ru": ["электронная коммерция", "экономика платформ", "производительность фирм", "цифровое внедрение", "малая розница", "инструментальные переменные"],
        },
        "authors": [
            {"given": "Marta", "family": "Kowalska", "affiliation": {"en": "Warsaw School of Economics", "uz": "Varshava iqtisodiyot maktabi", "ru": "Варшавская школа экономики"}, "city": "Warsaw", "country": "PL", "orcid": "0000-0002-1000-0051", "corresponding": True, "credit": ["Conceptualization", "Formal analysis", "Writing – original draft"]},
            {"given": "Sardor", "family": "Rakhmonov", "affiliation": {"en": "Tashkent University of Information Technologies", "uz": "Toshkent axborot texnologiyalari universiteti", "ru": "Ташкентский университет информационных технологий"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0052", "credit": ["Software", "Data curation"]},
        ],
    },
    {
        "section": "management-entrepreneurship-labour",
        "issue": 1,
        "jel": ["J24", "J61", "O15"],
        "title": {
            "en": "Return Migration, Skill Transfer and Firm Creation: Evidence from a Household Panel",
            "uz": "Qaytish migratsiyasi, koʻnikma uzatilishi va korxona tashkil etish: uy xoʻjaliklari paneli asosida",
            "ru": "Возвратная миграция, передача навыков и создание фирм: данные панели домохозяйств",
        },
        "abstract": {
            "en": "Return migrants are often expected to bring back capital and skills that raise entrepreneurship at home, yet the counterfactual is hard to construct because migration is selective. We use an eight-wave household panel covering 12,800 households and exploit variation in destination-country labour demand shocks interacted with pre-existing migration networks to instrument for return. Return migration raises the probability of starting a non-agricultural business within three years by 8.4 percentage points, from a base of 6.1 per cent. The effect is driven by returnees from destinations where they worked in construction and services rather than agriculture, and it is present only for those who spent more than two years abroad. Firms founded by returnees are larger at entry, are more likely to register formally, and survive longer, but they do not grow faster conditional on survival. Remitted savings account for about a third of the effect; the remainder is associated with self-reported managerial and technical skills. We discuss implications for reintegration policy.",
            "uz": "Qaytgan migrantlar vatanida tadbirkorlikni oshiradigan kapital va koʻnikmalarni olib keladi deb kutiladi, ammo migratsiya tanlanma boʻlgani uchun kontrfaktualni qurish qiyin. Biz 12 800 uy xoʻjaligini qamrab olgan sakkiz toʻlqinli paneldan foydalanamiz va qaytishni instrumentlash uchun manzil mamlakatlaridagi mehnat talabi zarbalari hamda mavjud migratsiya tarmoqlarining oʻzaro taʼsiridan foydalanamiz. Qaytish migratsiyasi uch yil ichida qishloq xoʻjaligiga aloqasi boʻlmagan biznes ochish ehtimolini 6,1 foizlik bazadan 8,4 foiz punktga oshiradi. Taʼsir qurilish va xizmat koʻrsatish sohalarida ishlagan (qishloq xoʻjaligida emas) qaytganlar hisobiga yuzaga keladi va faqat chet elda ikki yildan ortiq boʻlganlarda kuzatiladi. Qaytganlar tashkil etgan korxonalar kirish paytida yirikroq, rasmiy roʻyxatdan oʻtish ehtimoli yuqoriroq va uzoqroq yashaydi, ammo omon qolish shartida tezroq oʻsmaydi. Yuborilgan jamgʻarmalar taʼsirning taxminan uchdan birini izohlaydi; qolgani boshqaruv va texnik koʻnikmalar bilan bogʻliq. Reintegratsiya siyosati uchun xulosalar muhokama qilinadi.",
            "ru": "От возвратных мигрантов обычно ожидают привнесения капитала и навыков, повышающих предпринимательство на родине, однако контрфактическую ситуацию трудно построить, поскольку миграция селективна. Мы используем панель домохозяйств из восьми волн, охватывающую 12 800 домохозяйств, и применяем взаимодействие шоков спроса на труд в странах назначения с уже существующими миграционными сетями как инструмент для возвращения. Возвратная миграция повышает вероятность открытия несельскохозяйственного бизнеса в течение трёх лет на 8,4 процентных пункта при базовом уровне 6,1 процента. Эффект обеспечивают вернувшиеся из мест, где они работали в строительстве и услугах, а не в сельском хозяйстве, и он проявляется только у тех, кто провёл за рубежом более двух лет. Фирмы, основанные вернувшимися, крупнее при входе, чаще регистрируются формально и дольше выживают, но при условии выживания растут не быстрее. Переведённые сбережения объясняют около трети эффекта; остальное связано с управленческими и техническими навыками. Обсуждаются выводы для политики реинтеграции.",
        },
        "keywords": {
            "en": ["return migration", "entrepreneurship", "human capital", "remittances", "household panel", "firm entry"],
            "uz": ["qaytish migratsiyasi", "tadbirkorlik", "inson kapitali", "pul oʻtkazmalari", "uy xoʻjaliklari paneli", "korxona kirishi"],
            "ru": ["возвратная миграция", "предпринимательство", "человеческий капитал", "денежные переводы", "панель домохозяйств", "вход фирм"],
        },
        "authors": [
            {"given": "Rashid", "family": "Alimov", "affiliation": {"en": "National University", "uz": "Milliy universitet", "ru": "Национальный университет"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0061", "corresponding": True, "credit": ["Conceptualization", "Formal analysis"]},
            {"given": "Hiroshi", "family": "Tanaka", "affiliation": {"en": "Hitotsubashi University", "uz": "Hitotsubashi universiteti", "ru": "Университет Хитоцубаси"}, "city": "Tokyo", "country": "JP", "orcid": "0000-0002-1000-0062", "credit": ["Methodology", "Writing – review & editing"]},
        ],
    },
    {
        "section": "public-finance-taxation-customs",
        "issue": 1,
        "jel": ["H25", "H26", "O17"],
        "title": {
            "en": "Electronic Invoicing and VAT Compliance: A Regression Discontinuity Design",
            "uz": "Elektron hisob-faktura va QQS boʻyicha rioya: regressiya uzilishi dizayni",
            "ru": "Электронные счета-фактуры и соблюдение НДС: дизайн регрессионного разрыва",
        },
        "abstract": {
            "en": "Mandatory electronic invoicing is spreading rapidly through emerging economies on the argument that it curbs value-added tax evasion, but credible estimates of its effect remain scarce. We exploit a turnover threshold above which electronic invoicing became compulsory, using administrative tax records for 74,000 firms and a regression discontinuity design with manipulation testing. Firms just above the threshold report 12.6 per cent more taxable sales and claim 4.1 per cent fewer input credits than firms just below, implying a net VAT revenue gain of about 0.21 per cent of GDP from the affected segment. Reported effects appear within two quarters and persist for at least three years. We find substantial bunching just below the threshold, equivalent to 3.4 per cent of firms in the affected range, but the estimates are robust to donut-hole specifications. Compliance costs measured by accounting expenditure rise by 9 per cent for small firms, offsetting roughly a fifth of the revenue gain in welfare terms. The results support mandatory electronic invoicing while highlighting the case for threshold design that limits the burden on the smallest taxpayers.",
            "uz": "Majburiy elektron hisob-faktura qoʻshilgan qiymat soligʻidan qochishni kamaytiradi degan dalil bilan rivojlanayotgan iqtisodiyotlarda tez tarqalmoqda, ammo uning taʼsiri boʻyicha ishonchli baholar kam. Biz elektron hisob-faktura majburiy boʻlgan aylanma chegarasidan foydalanamiz: 74 000 korxonaning maʼmuriy soliq yozuvlari va manipulyatsiyani tekshirish bilan regressiya uzilishi dizayni qoʻllanilgan. Chegaradan sal yuqori korxonalar sal pastdagilarga nisbatan 12,6 foiz koʻproq soliqqa tortiladigan sotuvni koʻrsatadi va 4,1 foiz kamroq kirim kreditini talab qiladi — bu taʼsir doirasidagi segmentdan YaIMning taxminan 0,21 foizi miqdorida sof QQS tushumi oʻsishini bildiradi. Taʼsir ikki chorak ichida namoyon boʻladi va kamida uch yil saqlanadi. Chegaradan sal pastda sezilarli toʻplanish kuzatiladi — taʼsir doirasidagi korxonalarning 3,4 foiziga teng — ammo baholar «donut» spetsifikatsiyalarida ham barqaror. Buxgalteriya xarajatlari bilan oʻlchangan rioya xarajatlari kichik korxonalarda 9 foizga oshadi, bu farovonlik nuqtayi nazaridan tushum yutugʻining taxminan beshdan birini qoplaydi. Natijalar majburiy elektron hisob-fakturani qoʻllab-quvvatlaydi va eng kichik soliq toʻlovchilar yukini cheklaydigan chegara dizayni zarurligini koʻrsatadi.",
            "ru": "Обязательное электронное выставление счетов быстро распространяется в развивающихся экономиках под аргументом, что оно сдерживает уклонение от НДС, однако убедительных оценок эффекта мало. Мы используем порог оборота, выше которого электронные счета-фактуры стали обязательными, применяя административные налоговые записи 74 000 фирм и дизайн регрессионного разрыва с тестированием манипулирования. Фирмы чуть выше порога декларируют на 12,6 процента больше облагаемых продаж и заявляют на 4,1 процента меньше входящих вычетов, чем фирмы чуть ниже, что даёт чистый прирост поступлений НДС около 0,21 процента ВВП по затронутому сегменту. Эффекты проявляются в течение двух кварталов и сохраняются не менее трёх лет. Мы обнаруживаем существенное скопление чуть ниже порога, эквивалентное 3,4 процента фирм в затронутом диапазоне, но оценки устойчивы к «донат»-спецификациям. Издержки соблюдения, измеренные расходами на бухгалтерию, растут на 9 процентов у малых фирм, что в терминах благосостояния компенсирует примерно пятую часть прироста доходов. Результаты поддерживают обязательное электронное выставление счетов и подчёркивают важность порога, ограничивающего нагрузку на мельчайших налогоплательщиков.",
        },
        "keywords": {
            "en": ["value-added tax", "tax compliance", "electronic invoicing", "regression discontinuity", "administrative data", "informality"],
            "uz": ["qoʻshilgan qiymat soligʻi", "soliq rioyasi", "elektron hisob-faktura", "regressiya uzilishi", "maʼmuriy maʼlumotlar", "norasmiylik"],
            "ru": ["налог на добавленную стоимость", "налоговое соблюдение", "электронные счета-фактуры", "регрессионный разрыв", "административные данные", "неформальность"],
        },
        "authors": [
            {"given": "Kamola", "family": "Yusupova", "affiliation": {"en": "Institute of Economic Research", "uz": "Iqtisodiy tadqiqotlar instituti", "ru": "Институт экономических исследований"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0071", "corresponding": True, "credit": ["Conceptualization", "Formal analysis", "Data curation"]},
            {"given": "Sergey", "family": "Volkov", "affiliation": {"en": "Institute of Economics and Industrial Engineering", "uz": "Iqtisodiyot va sanoat muhandisligi instituti", "ru": "Институт экономики и организации промышленного производства"}, "city": "Novosibirsk", "country": "RU", "orcid": "0000-0002-1000-0072", "credit": ["Methodology", "Validation"]},
        ],
    },
    {
        "section": "international-trade-integration",
        "issue": 1,
        "jel": ["F14", "F15", "O19"],
        "title": {
            "en": "Regional Integration and Export Diversification: Gravity Evidence from Landlocked Economies",
            "uz": "Mintaqaviy integratsiya va eksport diversifikatsiyasi: dengizga chiqishi yoʻq iqtisodiyotlar boʻyicha gravitatsion dalillar",
            "ru": "Региональная интеграция и диверсификация экспорта: гравитационные данные по странам без выхода к морю",
        },
        "abstract": {
            "en": "Landlocked economies face transit costs that standard gravity models capture only through distance, understating the value of transit agreements. We estimate a structural gravity model on bilateral product-level trade for 26 landlocked economies from 2000 to 2023, adding explicit measures of transit-corridor agreements and border-crossing time collected from corridor performance surveys. Transit agreements reduce trade costs by an amount equivalent to a 4.7 percentage point tariff reduction, and the effect is twice as large for time-sensitive products. Signing a transit agreement raises the number of exported product lines by 9 per cent within five years, mostly through the survival of new export relationships rather than through more entry. The extensive-margin effect is concentrated in agricultural and light manufacturing products and is absent for mineral exports. Simulations of a fully implemented regional transit regime imply a 14 per cent increase in intra-regional trade and a measurable reduction in export concentration. We conclude that corridor governance is as consequential as tariff policy for diversification.",
            "uz": "Dengizga chiqishi yoʻq iqtisodiyotlar tranzit xarajatlariga duch keladi; standart gravitatsion modellar ularni faqat masofa orqali hisobga oladi va tranzit bitimlarining qiymatini kam baholaydi. Biz 2000–2023-yillarda 26 ta dengizga chiqishi yoʻq iqtisodiyot boʻyicha ikki tomonlama mahsulot darajasidagi savdo uchun strukturaviy gravitatsion modelni baholadik va tranzit koridori bitimlari hamda koridor samaradorligi soʻrovlaridan olingan chegara kesib oʻtish vaqti oʻlchovlarini qoʻshdik. Tranzit bitimlari savdo xarajatlarini 4,7 foiz punktlik tarif pasayishiga teng miqdorda kamaytiradi va vaqtga sezgir mahsulotlarda taʼsir ikki barobar kuchli. Tranzit bitimini imzolash besh yil ichida eksport qilinadigan mahsulot turlari sonini 9 foizga oshiradi — asosan yangi eksport aloqalarining saqlanib qolishi hisobiga, yangi kirish hisobiga emas. Ekstensiv chegaradagi taʼsir qishloq xoʻjaligi va yengil sanoat mahsulotlarida toʻplangan, mineral eksportda esa yoʻq. Toʻliq amalga oshirilgan mintaqaviy tranzit rejimi simulyatsiyasi mintaqa ichidagi savdoning 14 foizga oshishini va eksport konsentratsiyasining sezilarli pasayishini koʻrsatadi. Xulosa: diversifikatsiya uchun koridor boshqaruvi tarif siyosati kabi muhim.",
            "ru": "Страны без выхода к морю несут транзитные издержки, которые стандартные гравитационные модели учитывают лишь через расстояние, недооценивая значение транзитных соглашений. Мы оцениваем структурную гравитационную модель на двусторонней торговле по товарным позициям для 26 стран без выхода к морю за 2000–2023 годы, добавляя явные показатели соглашений по транзитным коридорам и времени пересечения границы из обследований эффективности коридоров. Транзитные соглашения снижают торговые издержки на величину, эквивалентную снижению тарифа на 4,7 процентных пункта, причём для чувствительных ко времени товаров эффект вдвое больше. Подписание транзитного соглашения увеличивает число экспортируемых товарных позиций на 9 процентов за пять лет, главным образом за счёт выживания новых экспортных связей, а не роста числа входов. Эффект на экстенсивной марже сосредоточен в сельскохозяйственной продукции и лёгкой промышленности и отсутствует для минерального экспорта. Моделирование полностью реализованного регионального транзитного режима даёт рост внутрирегиональной торговли на 14 процентов и заметное снижение концентрации экспорта. Мы заключаем, что управление коридорами не менее значимо для диверсификации, чем тарифная политика.",
        },
        "keywords": {
            "en": ["gravity model", "export diversification", "regional integration", "transit corridors", "landlocked economies", "trade costs"],
            "uz": ["gravitatsion model", "eksport diversifikatsiyasi", "mintaqaviy integratsiya", "tranzit koridorlari", "dengizga chiqishi yoʻq iqtisodiyotlar", "savdo xarajatlari"],
            "ru": ["гравитационная модель", "диверсификация экспорта", "региональная интеграция", "транзитные коридоры", "страны без выхода к морю", "торговые издержки"],
        },
        "authors": [
            {"given": "Elena", "family": "Sokolova", "affiliation": {"en": "Graduate School of Economics", "uz": "Iqtisodiyot oliy maktabi", "ru": "Высшая школа экономики"}, "city": "Almaty", "country": "KZ", "orcid": "0000-0002-1000-0081", "corresponding": True, "credit": ["Conceptualization", "Formal analysis"]},
            {"given": "Hiroshi", "family": "Tanaka", "affiliation": {"en": "Hitotsubashi University", "uz": "Hitotsubashi universiteti", "ru": "Университет Хитоцубаси"}, "city": "Tokyo", "country": "JP", "orcid": "0000-0002-1000-0082", "credit": ["Methodology"]},
            {"given": "Nodira", "family": "Rakhimova", "affiliation": {"en": "Institute of Economic Research", "uz": "Iqtisodiy tadqiqotlar instituti", "ru": "Институт экономических исследований"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0083", "credit": ["Supervision", "Writing – review & editing"]},
        ],
    },
    {
        "section": "macroeconomics-monetary-fiscal-policy",
        "issue": 2,
        "jel": ["E62", "H63", "E32"],
        "title": {
            "en": "Fiscal Rules and the Cyclicality of Public Spending in Commodity Exporters",
            "uz": "Xomashyo eksportchilarida fiskal qoidalar va davlat xarajatlarining sikllilik darajasi",
            "ru": "Фискальные правила и цикличность государственных расходов у экспортёров сырья",
        },
        "abstract": {
            "en": "Commodity exporters have long spent procyclically, amplifying the volatility their economies already face. We ask whether the fiscal rules adopted since 2005 have changed that behaviour. Using a panel of 42 commodity-exporting economies from 1995 to 2023 and a synthetic control approach applied rule by rule, we estimate the change in the cyclicality of primary expenditure after adoption. Structural balance rules reduce the elasticity of primary spending to the commodity price cycle from 0.46 to 0.19, while nominal expenditure ceilings reduce it only to 0.34 and debt-brake rules have no detectable effect. Rules accompanied by an independent fiscal council and by an escape clause with an explicit return path perform substantially better than rules without them; rules that were suspended more than once show no benefit at all. We find no evidence that rules reduced total spending levels — the change is in timing, not in size. Public investment is the component whose cyclicality falls most, which matters because it is also the component most often cut in downturns.",
            "uz": "Xomashyo eksportchilari uzoq vaqt davomida siklga mos xarajat qilib, iqtisodiyotlaridagi tebranishlarni kuchaytirib keldi. Biz 2005-yildan beri qabul qilingan fiskal qoidalar bu xatti-harakatni oʻzgartirganmi degan savolni qoʻyamiz. 1995–2023-yillarda 42 ta xomashyo eksportchisi panelidan va har bir qoidaga alohida qoʻllangan sintetik nazorat yondashuvidan foydalanib, qoida qabul qilingandan keyin birlamchi xarajatlar siklliligining oʻzgarishini baholaymiz. Strukturaviy balans qoidalari birlamchi xarajatlarning xomashyo narxi sikliga elastikligini 0,46 dan 0,19 gacha kamaytiradi; nominal xarajat shiftlari uni faqat 0,34 gacha tushiradi, qarz tormozi qoidalari esa sezilarli taʼsir koʻrsatmaydi. Mustaqil fiskal kengash va aniq qaytish yoʻli koʻrsatilgan istisno bandi bilan birga kelgan qoidalar bunday elementlarsiz qoidalardan sezilarli ustun; bir necha marta toʻxtatilgan qoidalar umuman foyda bermaydi. Qoidalar umumiy xarajat darajasini kamaytirgani haqida dalil topilmadi — oʻzgarish hajmda emas, vaqtda. Sikllilik eng koʻp pasaygan komponent — davlat investitsiyasi, bu esa muhim, chunki aynan u tanazzul davrida koʻpincha qisqartiriladi.",
            "ru": "Экспортёры сырья долгое время расходовали проциклически, усиливая волатильность, с которой их экономики и так сталкиваются. Мы спрашиваем, изменили ли это поведение фискальные правила, принятые после 2005 года. Используя панель из 42 сырьевых экономик за 1995–2023 годы и метод синтетического контроля, применённый к каждому правилу отдельно, мы оцениваем изменение цикличности первичных расходов после принятия. Правила структурного баланса снижают эластичность первичных расходов по сырьевому ценовому циклу с 0,46 до 0,19, тогда как номинальные потолки расходов снижают её лишь до 0,34, а правила долгового тормоза заметного эффекта не дают. Правила, сопровождаемые независимым фискальным советом и оговоркой об исключениях с явным путём возврата, работают существенно лучше; правила, приостанавливавшиеся более одного раза, выгоды не приносят вовсе. Свидетельств того, что правила снизили общий уровень расходов, мы не находим — меняется тайминг, а не размер. Сильнее всего падает цикличность государственных инвестиций, что важно, поскольку именно их чаще всего сокращают в спад.",
        },
        "keywords": {
            "en": ["fiscal rules", "procyclicality", "commodity exporters", "public investment", "synthetic control", "fiscal councils"],
            "uz": ["fiskal qoidalar", "siklga moslik", "xomashyo eksportchilari", "davlat investitsiyasi", "sintetik nazorat", "fiskal kengashlar"],
            "ru": ["фискальные правила", "процикличность", "экспортёры сырья", "государственные инвестиции", "синтетический контроль", "фискальные советы"],
        },
        "authors": [
            {"given": "Timur", "family": "Abdullayev", "affiliation": {"en": "University of Economics and Finance", "uz": "Iqtisodiyot va moliya universiteti", "ru": "Университет экономики и финансов"}, "city": "Samarkand", "country": "UZ", "orcid": "0000-0002-1000-0091", "corresponding": True, "credit": ["Conceptualization", "Formal analysis", "Writing – original draft"]},
            {"given": "Michael", "family": "Brennan", "affiliation": {"en": "University of Manchester", "uz": "Manchester universiteti", "ru": "Манчестерский университет"}, "city": "Manchester", "country": "GB", "orcid": "0000-0002-1000-0092", "credit": ["Methodology", "Supervision"]},
        ],
    },
    {
        "section": "economic-theory-methodology",
        "issue": 2,
        "jel": ["C52", "C53", "O47"],
        "title": {
            "en": "Machine Learning for Policy Evaluation: When Do Flexible Estimators Help?",
            "uz": "Siyosatni baholashda mashinali oʻqitish: moslashuvchan baholovchilar qachon foyda beradi?",
            "ru": "Машинное обучение в оценке политики: когда гибкие оценки полезны?",
        },
        "abstract": {
            "en": "Flexible machine learning estimators are increasingly used for causal inference in economics, but guidance on when they improve on conventional methods is largely informal. We run a systematic simulation study covering 1,080 data-generating processes that vary in sample size, dimensionality, treatment-effect heterogeneity, overlap and the smoothness of the nuisance functions, and we evaluate double machine learning, causal forests, augmented inverse probability weighting and conventional matching against the same estimands. Machine learning estimators dominate when the propensity score is a smooth but strongly non-linear function of many covariates and the sample exceeds roughly 2,000 observations; below that, cross-fitting variance dominates and conventional estimators are more accurate. Under weak overlap, all estimators are badly biased, and flexible methods are not more robust — a finding that contradicts a common belief in applied work. We replicate three published policy evaluations from development economics and show that the choice of estimator changes the point estimate by less than one standard error in two of them and reverses the sign in the third, where overlap is poor. We provide a decision rule and reproducible code.",
            "uz": "Moslashuvchan mashinali oʻqitish baholovchilari iqtisodiyotda sababiy xulosa uchun tobora koʻproq ishlatilmoqda, ammo ular anʼanaviy usullardan qachon ustun boʻlishi haqidagi yoʻriqnoma asosan norasmiy. Biz tanlanma hajmi, oʻlchamlilik, taʼsir heterogenligi, qoplama va yordamchi funksiyalar silliqligi boʻyicha farq qiluvchi 1 080 ta maʼlumot generatsiya jarayonini qamrab olgan tizimli simulyatsiya oʻtkazdik va bir xil baholanuvchilar boʻyicha ikki tomonlama mashinali oʻqitish, sababiy oʻrmonlar, kengaytirilgan teskari ehtimollik tortish va anʼanaviy moslashtirishni taqqosladik. Mashinali oʻqitish baholovchilari, agar tendensiya bahosi koʻp kovariatlarning silliq, ammo kuchli chiziqli boʻlmagan funksiyasi boʻlsa va tanlanma taxminan 2 000 kuzatuvdan oshsa, ustunlik qiladi; bundan past hajmda kross-fitting dispersiyasi ustun keladi va anʼanaviy baholovchilar aniqroq. Zaif qoplama sharoitida barcha baholovchilar jiddiy siljigan boʻladi va moslashuvchan usullar chidamliroq emas — bu amaliy ishlardagi keng tarqalgan qarashga zid. Rivojlanish iqtisodiyotidan uchta chop etilgan baholashni takrorlab, baholovchi tanlovi ikkitasida nuqta bahosini bir standart xatodan kamroq oʻzgartirishini, qoplama yomon boʻlgan uchinchisida esa ishorani teskari qilishini koʻrsatamiz. Qaror qoidasi va takrorlanadigan kod taqdim etiladi.",
            "ru": "Гибкие оценки на основе машинного обучения всё чаще применяются для причинного вывода в экономике, но рекомендации о том, когда они превосходят традиционные методы, в основном неформальны. Мы проводим систематическое симуляционное исследование, охватывающее 1 080 процессов генерации данных, различающихся по размеру выборки, размерности, гетерогенности эффекта, перекрытию и гладкости вспомогательных функций, и сравниваем двойное машинное обучение, каузальные леса, дополненное взвешивание обратной вероятностью и традиционный мэтчинг на одних и тех же оцениваемых величинах. Оценки машинного обучения доминируют, когда склонность к участию — гладкая, но сильно нелинейная функция многих ковариат, а выборка превышает примерно 2 000 наблюдений; ниже этого порога преобладает дисперсия кросс-фиттинга, и традиционные оценки точнее. При слабом перекрытии все оценки сильно смещены, а гибкие методы не более устойчивы — вывод, противоречащий распространённому мнению в прикладных работах. Мы воспроизводим три опубликованные оценки политики из экономики развития и показываем, что выбор оценки меняет точечную оценку менее чем на одну стандартную ошибку в двух случаях и меняет знак в третьем, где перекрытие плохое. Предлагаются решающее правило и воспроизводимый код.",
        },
        "keywords": {
            "en": ["machine learning", "causal inference", "policy evaluation", "double machine learning", "simulation study", "overlap"],
            "uz": ["mashinali oʻqitish", "sababiy xulosa", "siyosatni baholash", "ikki tomonlama mashinali oʻqitish", "simulyatsiya tadqiqoti", "qoplama"],
            "ru": ["машинное обучение", "причинный вывод", "оценка политики", "двойное машинное обучение", "симуляционное исследование", "перекрытие"],
        },
        "authors": [
            {"given": "Zarina", "family": "Ismailova", "affiliation": {"en": "Institute of Forecasting and Macroeconomic Research", "uz": "Prognozlashtirish va makroiqtisodiy tadqiqotlar instituti", "ru": "Институт прогнозирования и макроэкономических исследований"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0101", "corresponding": True, "credit": ["Conceptualization", "Software", "Formal analysis"]},
            {"given": "Marta", "family": "Kowalska", "affiliation": {"en": "Warsaw School of Economics", "uz": "Varshava iqtisodiyot maktabi", "ru": "Варшавская школа экономики"}, "city": "Warsaw", "country": "PL", "orcid": "0000-0002-1000-0102", "credit": ["Methodology", "Validation"]},
        ],
    },
    {
        "section": "regional-sectoral-development",
        "issue": 2,
        "jel": ["R11", "O18", "H54"],
        "title": {
            "en": "Road Quality and Regional Income Disparities: Evidence from a Rehabilitation Programme",
            "uz": "Yoʻl sifati va hududiy daromad tafovutlari: taʼmirlash dasturi misolida",
            "ru": "Качество дорог и региональные различия в доходах: опыт программы реконструкции",
        },
        "abstract": {
            "en": "Transport infrastructure is the largest single item in many public investment programmes, yet estimates of its regional effects are sensitive to the endogenous placement of roads. We study a rehabilitation programme that upgraded 2,900 kilometres of regional roads according to an engineering condition index, and we use the index threshold that determined eligibility to identify effects. Districts whose roads were upgraded show 7.2 per cent higher household consumption after four years and a 14 per cent increase in the number of registered non-farm enterprises, relative to districts just below the threshold. Night-light intensity confirms the pattern. Effects are concentrated in districts within 60 kilometres of a city of more than 100,000 inhabitants, and are indistinguishable from zero beyond that distance — evidence of market access rather than of local construction demand. We find a redistribution of activity from adjacent districts amounting to about 30 per cent of the measured gain, so aggregate effects are smaller than district-level estimates suggest. We conclude that connectivity investments should be evaluated at the regional rather than the district level.",
            "uz": "Transport infratuzilmasi koʻplab davlat investitsiya dasturlarida eng yirik moddadir, ammo uning hududiy taʼsiri boʻyicha baholar yoʻllarning endogen joylashuviga sezgir. Biz muhandislik holati indeksiga koʻra 2 900 kilometr hududiy yoʻlni yaxshilagan taʼmirlash dasturini oʻrgandik va tanlab olishni belgilagan indeks chegarasidan taʼsirni aniqlash uchun foydalandik. Yoʻllari yaxshilangan tumanlarda toʻrt yildan keyin uy xoʻjaliklari isteʼmoli chegaradan sal pastdagi tumanlarga nisbatan 7,2 foizga yuqori va roʻyxatdan oʻtgan nodehqonchilik korxonalari soni 14 foizga koʻp. Tungi yorugʻlik intensivligi bu manzarani tasdiqlaydi. Taʼsir aholisi 100 000 dan ortiq shahardan 60 kilometr radiusdagi tumanlarda toʻplangan va bu masofadan tashqarida noldan farq qilmaydi — bu mahalliy qurilish talabidan emas, bozorga chiqish imkoniyatidan dalolat beradi. Qoʻshni tumanlardan faoliyat qayta taqsimlanishi oʻlchangan yutuqning taxminan 30 foizini tashkil etadi, shuning uchun jami taʼsir tuman darajasidagi baholarga qaraganda kichikroq. Xulosa: bogʻlanish investitsiyalarini tuman emas, hudud darajasida baholash kerak.",
            "ru": "Транспортная инфраструктура — крупнейшая статья многих программ государственных инвестиций, однако оценки её региональных эффектов чувствительны к эндогенному размещению дорог. Мы изучаем программу реконструкции, обновившую 2 900 километров региональных дорог по инженерному индексу состояния, и используем пороговое значение индекса, определявшее право на участие, для идентификации эффектов. В районах, где дороги были обновлены, потребление домохозяйств через четыре года выше на 7,2 процента, а число зарегистрированных несельскохозяйственных предприятий — на 14 процентов по сравнению с районами чуть ниже порога. Интенсивность ночного освещения подтверждает эту картину. Эффекты сосредоточены в районах в пределах 60 километров от города с населением более 100 000 человек и неотличимы от нуля за этим расстоянием — свидетельство в пользу доступа к рынкам, а не локального спроса на строительство. Мы обнаруживаем перераспределение активности из соседних районов, составляющее около 30 процентов измеренного выигрыша, поэтому совокупные эффекты меньше, чем следует из районных оценок. Мы заключаем, что инвестиции в связанность следует оценивать на региональном, а не районном уровне.",
        },
        "keywords": {
            "en": ["transport infrastructure", "regional development", "market access", "night lights", "regression discontinuity", "public investment"],
            "uz": ["transport infratuzilmasi", "hududiy rivojlanish", "bozorga chiqish", "tungi yorugʻlik", "regressiya uzilishi", "davlat investitsiyasi"],
            "ru": ["транспортная инфраструктура", "региональное развитие", "доступ к рынкам", "ночное освещение", "регрессионный разрыв", "государственные инвестиции"],
        },
        "authors": [
            {"given": "Bekzod", "family": "Toshmatov", "affiliation": {"en": "Centre for Regional Studies", "uz": "Hududiy tadqiqotlar markazi", "ru": "Центр региональных исследований"}, "city": "Bukhara", "country": "UZ", "orcid": "0000-0002-1000-0111", "corresponding": True, "credit": ["Conceptualization", "Formal analysis"]},
            {"given": "Aidos", "family": "Nurgaliyev", "affiliation": {"en": "Graduate School of Economics", "uz": "Iqtisodiyot oliy maktabi", "ru": "Высшая школа экономики"}, "city": "Almaty", "country": "KZ", "orcid": "0000-0002-1000-0112", "credit": ["Data curation", "Visualization"]},
        ],
    },
    {
        "section": "management-entrepreneurship-labour",
        "issue": 2,
        "jel": ["M13", "J23", "L25"],
        "title": {
            "en": "Management Practices and Firm Performance in Family-Owned Manufacturing",
            "uz": "Oilaviy ishlab chiqarish korxonalarida boshqaruv amaliyoti va samaradorlik",
            "ru": "Управленческие практики и результативность семейных производственных компаний",
        },
        "abstract": {
            "en": "Differences in management practices explain a substantial share of the productivity gap between firms, but the evidence comes mostly from large economies and from firms with professional managers. We survey 1,150 family-owned manufacturing firms using an adapted World Management Survey instrument and match the responses to administrative accounting records. A one standard deviation increase in the management score is associated with 18 per cent higher labour productivity and 11 per cent higher sales growth. Practices related to monitoring and target setting carry almost all of the association; incentive practices carry none once family ownership of management positions is controlled for. Firms in which at least one manager is not a family member score 0.42 standard deviations higher, and the gap widens with firm size. We use the death or retirement of a founding owner as a source of variation and find that succession by a non-family manager raises the management score and productivity, whereas succession within the family does not. The results point to managerial labour market frictions rather than to knowledge constraints.",
            "uz": "Boshqaruv amaliyotidagi farqlar korxonalar oʻrtasidagi unumdorlik tafovutining sezilarli qismini izohlaydi, ammo dalillar asosan yirik iqtisodiyotlar va professional menejerlarga ega korxonalardan olingan. Biz moslashtirilgan World Management Survey vositasidan foydalanib 1 150 ta oilaviy ishlab chiqarish korxonasini soʻrovdan oʻtkazdik va javoblarni maʼmuriy buxgalteriya yozuvlari bilan solishtirdik. Boshqaruv bahosining bir standart ogʻishga oshishi mehnat unumdorligining 18 foiz va sotuv oʻsishining 11 foiz yuqori boʻlishi bilan bogʻliq. Bogʻliqlikning deyarli barchasini monitoring va maqsad belgilash amaliyotlari beradi; boshqaruv lavozimlarining oilaviy egaligi nazorat qilinganda ragʻbatlantirish amaliyotlari hech qanday bogʻliqlik bermaydi. Kamida bitta menejeri oila aʼzosi boʻlmagan korxonalar bahosi 0,42 standart ogʻishga yuqori va bu farq korxona hajmi bilan kengayadi. Asoschi egasining vafoti yoki nafaqaga chiqishini oʻzgaruvchanlik manbai sifatida ishlatib, oila aʼzosi boʻlmagan menejerga oʻtish boshqaruv bahosini va unumdorlikni oshirishini, oila ichidagi oʻtish esa oshirmasligini aniqladik. Natijalar bilim cheklovlariga emas, boshqaruv mehnat bozoridagi ishqalanishlarga ishora qiladi.",
            "ru": "Различия в управленческих практиках объясняют значительную часть разрыва в производительности между фирмами, но доказательства получены в основном на крупных экономиках и на фирмах с профессиональными менеджерами. Мы опрашиваем 1 150 семейных производственных компаний по адаптированному инструменту World Management Survey и сопоставляем ответы с административной бухгалтерской отчётностью. Рост управленческого балла на одно стандартное отклонение связан с производительностью труда выше на 18 процентов и ростом продаж выше на 11 процентов. Почти всю связь обеспечивают практики мониторинга и постановки целей; практики стимулирования не дают ничего после контроля на семейное владение управленческими позициями. Фирмы, где хотя бы один менеджер не является членом семьи, набирают на 0,42 стандартного отклонения больше, и разрыв растёт с размером фирмы. Используя смерть или выход на пенсию основателя как источник вариации, мы находим, что переход управления к менеджеру не из семьи повышает управленческий балл и производительность, тогда как передача внутри семьи — нет. Результаты указывают на трения на рынке управленческого труда, а не на ограничения знаний.",
        },
        "keywords": {
            "en": ["management practices", "family firms", "productivity", "manufacturing", "succession", "survey data"],
            "uz": ["boshqaruv amaliyoti", "oilaviy korxonalar", "unumdorlik", "ishlab chiqarish", "vorislik", "soʻrov maʼlumotlari"],
            "ru": ["управленческие практики", "семейные фирмы", "производительность", "обрабатывающая промышленность", "преемственность", "данные опросов"],
        },
        "authors": [
            {"given": "Rashid", "family": "Alimov", "affiliation": {"en": "National University", "uz": "Milliy universitet", "ru": "Национальный университет"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0121", "corresponding": True, "credit": ["Conceptualization", "Investigation"]},
            {"given": "Ayşe", "family": "Demir", "affiliation": {"en": "Middle East Technical University", "uz": "Yaqin Sharq texnika universiteti", "ru": "Ближневосточный технический университет"}, "city": "Ankara", "country": "TR", "orcid": "0000-0002-1000-0122", "credit": ["Formal analysis", "Writing – review & editing"]},
        ],
    },
    # ------------------------------------------------------------- Online First
    {
        "section": "finance-banking-investment",
        "issue": None,
        "jel": ["G51", "G21", "I32"],
        "title": {
            "en": "Digital Credit and Household Debt: Short-Term Relief or Long-Term Burden?",
            "uz": "Raqamli kredit va uy xoʻjaliklari qarzi: qisqa muddatli yengillikmi yoki uzoq muddatli yukmi?",
            "ru": "Цифровой кредит и долг домохозяйств: краткосрочное облегчение или долгосрочное бремя?",
        },
        "abstract": {
            "en": "Mobile-based instalment credit has expanded rapidly among households with no previous formal borrowing history, and its welfare consequences are disputed. We link the loan-level records of a digital lender covering 380,000 borrowers to a household survey panel and estimate the effect of first-time digital borrowing using a credit-score cut-off as a discontinuity. Access raises consumption in the quarter of borrowing by 4.2 per cent and reduces the probability of reporting a missed essential expense by 6 percentage points, confirming a genuine liquidity benefit. Over eight quarters, however, borrowers just above the cut-off hold 31 per cent more total debt, are 5.7 percentage points more likely to be delinquent on any obligation, and show no gain in durable ownership or business investment. Effects are worse for borrowers who take a second loan within 30 days of repaying the first, a group representing 22 per cent of the sample. Interest rate caps in our simulation reduce the harm less effectively than cooling-off requirements between consecutive loans.",
            "uz": "Mobil boʻlib-boʻlib toʻlash krediti ilgari rasmiy qarz olish tarixiga ega boʻlmagan uy xoʻjaliklari orasida tez tarqaldi va uning farovonlikka taʼsiri bahsli. Biz 380 000 qarz oluvchini qamrab olgan raqamli kreditor yozuvlarini uy xoʻjaliklari soʻrovi paneli bilan bogʻladik va kredit balli chegarasini uzilish sifatida ishlatib, birinchi marta raqamli qarz olishning taʼsirini baholadik. Kreditga kirish qarz olingan chorakda isteʼmolni 4,2 foizga oshiradi va zaruriy xarajatni oʻtkazib yuborish ehtimolini 6 foiz punktga kamaytiradi — bu haqiqiy likvidlik foydasini tasdiqlaydi. Ammo sakkiz chorak davomida chegaradan sal yuqoridagi qarz oluvchilar 31 foiz koʻproq umumiy qarzga ega, har qanday majburiyat boʻyicha kechikish ehtimoli 5,7 foiz punktga yuqori va uzoq muddatli tovarlar yoki biznes investitsiyasida hech qanday yutuq koʻrsatmaydi. Birinchi kreditni toʻlagandan keyin 30 kun ichida ikkinchisini olgan qarz oluvchilarda (tanlanmaning 22 foizi) natija yomonroq. Simulyatsiyamizda foiz stavkasi cheklovlari zararni ketma-ket kreditlar orasidagi majburiy tanaffus talabiga qaraganda kamroq kamaytiradi.",
            "ru": "Мобильный рассрочный кредит быстро распространился среди домохозяйств без прежней истории формальных заимствований, и его влияние на благосостояние оспаривается. Мы связываем данные цифрового кредитора по 380 000 заёмщиков с панельным обследованием домохозяйств и оцениваем эффект первого цифрового займа, используя порог кредитного балла как разрыв. Доступ повышает потребление в квартале заимствования на 4,2 процента и снижает вероятность пропуска необходимого расхода на 6 процентных пунктов, подтверждая реальную выгоду от ликвидности. Однако за восемь кварталов заёмщики чуть выше порога имеют на 31 процент больше совокупного долга, на 5,7 процентных пункта чаще допускают просрочку по любому обязательству и не показывают прироста ни во владении товарами длительного пользования, ни в бизнес-инвестициях. Хуже результаты у тех, кто берёт второй заём в течение 30 дней после погашения первого, — это 22 процента выборки. В нашем моделировании ограничение процентных ставок снижает вред менее эффективно, чем требование паузы между последовательными займами.",
        },
        "keywords": {
            "en": ["digital credit", "household debt", "financial inclusion", "over-indebtedness", "regression discontinuity", "consumer protection"],
            "uz": ["raqamli kredit", "uy xoʻjaligi qarzi", "moliyaviy qamrov", "ortiqcha qarzdorlik", "regressiya uzilishi", "isteʼmolchi himoyasi"],
            "ru": ["цифровой кредит", "долг домохозяйств", "финансовая доступность", "чрезмерная задолженность", "регрессионный разрыв", "защита потребителей"],
        },
        "authors": [
            {"given": "Aziz", "family": "Karimov", "affiliation": {"en": "Banking and Finance Academy", "uz": "Bank-moliya akademiyasi", "ru": "Банковско-финансовая академия"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0131", "corresponding": True, "credit": ["Conceptualization", "Formal analysis", "Writing – original draft"]},
            {"given": "Sergey", "family": "Volkov", "affiliation": {"en": "Institute of Economics and Industrial Engineering", "uz": "Iqtisodiyot va sanoat muhandisligi instituti", "ru": "Институт экономики и организации промышленного производства"}, "city": "Novosibirsk", "country": "RU", "orcid": "0000-0002-1000-0132", "credit": ["Data curation", "Methodology"]},
        ],
    },
    {
        "section": "digital-economy-innovation",
        "issue": None,
        "jel": ["O31", "O38", "L52"],
        "title": {
            "en": "Do Research Subsidies Reach Productive Firms? Allocation and Additionality in an Innovation Programme",
            "uz": "Tadqiqot subsidiyalari unumli korxonalarga yetib boradimi? Innovatsion dasturda taqsimot va qoʻshimchalik",
            "ru": "Доходят ли исследовательские субсидии до продуктивных фирм? Распределение и дополнительность в инновационной программе",
        },
        "abstract": {
            "en": "Innovation subsidy programmes are judged on whether they raise research spending beyond what firms would have done anyway, but allocation quality is rarely examined alongside additionality. Using the complete application and scoring records of a national innovation grant programme with 6,700 applications over nine years, we study both. Grants raise recipient research spending by 0.71 units per unit of subsidy, so crowding-out is partial but real, and they raise patent applications by 24 per cent with no effect on revenue within four years. Allocation is only weakly related to measurable firm quality: pre-application productivity explains 4 per cent of the variation in scores, while the identity of the reviewing panel explains 19 per cent. Replacing panel scoring with a simple productivity-and-growth rule in a counterfactual allocation would raise programme-level additional research spending by 16 per cent at the same budget. We find no evidence of favouritism toward politically connected firms, but substantial noise in scoring. The results suggest that improving allocation may matter more than expanding budgets.",
            "uz": "Innovatsion subsidiya dasturlari korxonalar baribir qilgan xarajatdan ortiq tadqiqot sarfini oshirganiga qarab baholanadi, ammo taqsimot sifati qoʻshimchalik bilan birga kamdan-kam oʻrganiladi. Toʻqqiz yil davomida 6 700 ta arizani qamrab olgan milliy innovatsion grant dasturining toʻliq ariza va baholash yozuvlaridan foydalanib, ikkalasini ham oʻrganamiz. Grantlar oluvchining tadqiqot xarajatini har bir subsidiya birligiga 0,71 birlikka oshiradi — demak, siqib chiqarish qisman, lekin real; patent arizalari 24 foizga koʻpayadi, toʻrt yil ichida tushumga taʼsir yoʻq. Taqsimot oʻlchanadigan korxona sifati bilan faqat zaif bogʻliq: arizadan oldingi unumdorlik ballardagi farqning 4 foizini izohlaydi, baholovchi hayʼat kimligi esa 19 foizini. Kontrfaktual taqsimotda hayʼat baholashini oddiy unumdorlik va oʻsish qoidasi bilan almashtirish bir xil byudjetda dastur darajasidagi qoʻshimcha tadqiqot xarajatini 16 foizga oshiradi. Siyosiy aloqaga ega korxonalarga imtiyoz haqida dalil topilmadi, ammo baholashda sezilarli shovqin bor. Natijalar taqsimotni yaxshilash byudjetni kengaytirishdan muhimroq boʻlishi mumkinligini koʻrsatadi.",
            "ru": "Программы инновационных субсидий оценивают по тому, увеличивают ли они исследовательские расходы сверх того, что фирмы сделали бы и так, однако качество распределения редко изучается вместе с дополнительностью. Используя полные записи заявок и оценок национальной программы инновационных грантов с 6 700 заявками за девять лет, мы изучаем и то и другое. Гранты увеличивают исследовательские расходы получателей на 0,71 единицы на единицу субсидии, то есть вытеснение частичное, но реальное; число патентных заявок растёт на 24 процента без влияния на выручку в течение четырёх лет. Распределение лишь слабо связано с измеримым качеством фирм: производительность до подачи объясняет 4 процента вариации баллов, тогда как состав оценивающей коллегии — 19 процентов. Замена коллегиального оценивания простым правилом по производительности и росту в контрфактическом распределении увеличила бы дополнительные исследовательские расходы на уровне программы на 16 процентов при том же бюджете. Свидетельств фаворитизма в пользу политически связанных фирм мы не находим, но обнаруживаем значительный шум в оценках. Результаты позволяют предположить, что улучшение распределения может быть важнее расширения бюджета.",
        },
        "keywords": {
            "en": ["innovation policy", "research subsidies", "additionality", "grant allocation", "patents", "programme evaluation"],
            "uz": ["innovatsion siyosat", "tadqiqot subsidiyalari", "qoʻshimchalik", "grant taqsimoti", "patentlar", "dasturni baholash"],
            "ru": ["инновационная политика", "исследовательские субсидии", "дополнительность", "распределение грантов", "патенты", "оценка программ"],
        },
        "authors": [
            {"given": "Zarina", "family": "Ismailova", "affiliation": {"en": "Institute of Forecasting and Macroeconomic Research", "uz": "Prognozlashtirish va makroiqtisodiy tadqiqotlar instituti", "ru": "Институт прогнозирования и макроэкономических исследований"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0141", "corresponding": True, "credit": ["Conceptualization", "Formal analysis"]},
            {"given": "Michael", "family": "Brennan", "affiliation": {"en": "University of Manchester", "uz": "Manchester universiteti", "ru": "Манчестерский университет"}, "city": "Manchester", "country": "GB", "orcid": "0000-0002-1000-0142", "credit": ["Methodology", "Supervision"]},
            {"given": "Sardor", "family": "Rakhmonov", "affiliation": {"en": "Tashkent University of Information Technologies", "uz": "Toshkent axborot texnologiyalari universiteti", "ru": "Ташкентский университет информационных технологий"}, "city": "Tashkent", "country": "UZ", "orcid": "0000-0002-1000-0143", "credit": ["Software", "Data curation"]},
        ],
    },
]
