#!/usr/bin/env python
"""Fill the gettext catalogues from the hand-written translation tables.

* ``en``       — the source language: ``msgstr`` is the ``msgid``.
* ``uz``       — Uzbek Latin, from ``scripts/i18n_catalogue_*.py``.
* ``ru``       — Russian, from the same tables.
* ``uz_Cyrl``  — generated from the Uzbek Latin translation with
  :func:`apps.core.translit.to_cyrillic`, exactly as SPEC §10 prescribes.

Any ``msgid`` that has no entry in the tables is reported so it can be added;
the script exits non-zero in that case, which is what keeps the catalogues at
100 % coverage.

    python scripts/apply_translations.py            # fill and report
    python scripts/apply_translations.py --list     # only list what is missing
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE_DIR))
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings.dev")

import polib  # noqa: E402

from apps.core.translit import to_cyrillic  # noqa: E402
from scripts.i18n_catalogue_1 import PART_1  # noqa: E402
from scripts.i18n_catalogue_2 import PART_2  # noqa: E402
from scripts.i18n_catalogue_3 import PART_3  # noqa: E402
from scripts.i18n_catalogue_4 import PART_4  # noqa: E402
from scripts.i18n_catalogue_5 import PART_5  # noqa: E402

TRANSLATIONS: dict[str, tuple[str, str]] = {}
for part in (PART_1, PART_2, PART_3, PART_4, PART_5):
    TRANSLATIONS.update(part)

LOCALE_DIR = BASE_DIR / "locale"


def fill_locale(code: str, index: int | None) -> list[str]:
    """Fill one catalogue and return the ``msgid`` values it could not translate.

    ``index`` selects the tuple position (0 = Uzbek, 1 = Russian); ``None``
    means the msgstr is the msgid (the English source catalogue).
    """
    path = LOCALE_DIR / code / "LC_MESSAGES" / "django.po"
    if not path.exists():
        raise SystemExit(f"missing catalogue: {path}. Run `make messages` first.")

    catalogue = polib.pofile(str(path))
    catalogue.metadata["Language"] = code.replace("_", "-")
    catalogue.metadata["Content-Type"] = "text/plain; charset=UTF-8"
    catalogue.metadata["Plural-Forms"] = "nplurals=2; plural=(n != 1);"
    catalogue.metadata["Last-Translator"] = "ARER editorial office"
    catalogue.metadata["Language-Team"] = "ARER"

    missing: list[str] = []
    for entry in catalogue:
        if entry.obsolete:
            continue
        entry.flags = [f for f in entry.flags if f != "fuzzy"]

        if index is None:
            singular = entry.msgid
            plural = entry.msgid_plural or entry.msgid
        else:
            pair = TRANSLATIONS.get(entry.msgid)
            if pair is None:
                missing.append(entry.msgid)
                continue
            singular = pair[index]
            if entry.msgid_plural:
                plural_pair = TRANSLATIONS.get(entry.msgid_plural)
                if plural_pair is None:
                    missing.append(entry.msgid_plural)
                    continue
                plural = plural_pair[index]
            else:
                plural = singular

        if entry.msgid_plural:
            entry.msgstr_plural = {0: singular, 1: plural}
        else:
            entry.msgstr = singular

    catalogue.save(str(path))
    return missing


def fill_cyrillic() -> None:
    """Generate ``uz_Cyrl`` by transliterating the Uzbek Latin catalogue."""
    latin = polib.pofile(str(LOCALE_DIR / "uz" / "LC_MESSAGES" / "django.po"))
    latin_by_id = {e.msgid: e for e in latin if not e.obsolete}

    path = LOCALE_DIR / "uz_Cyrl" / "LC_MESSAGES" / "django.po"
    catalogue = polib.pofile(str(path))
    catalogue.metadata["Language"] = "uz-cyrl"
    catalogue.metadata["Content-Type"] = "text/plain; charset=UTF-8"
    catalogue.metadata["Plural-Forms"] = "nplurals=2; plural=(n != 1);"
    catalogue.metadata["Last-Translator"] = "generated by apps.core.translit"
    catalogue.metadata["Language-Team"] = "ARER"

    for entry in catalogue:
        if entry.obsolete:
            continue
        entry.flags = [f for f in entry.flags if f != "fuzzy"]
        source = latin_by_id.get(entry.msgid)
        if source is None:
            continue
        if entry.msgid_plural:
            entry.msgstr_plural = {
                0: to_cyrillic(source.msgstr_plural.get(0, "")),
                1: to_cyrillic(source.msgstr_plural.get(1, "")),
            }
        else:
            entry.msgstr = to_cyrillic(source.msgstr)
    catalogue.save(str(path))


def main() -> int:
    """Fill every catalogue and report coverage."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true", help="only list missing msgids")
    args = parser.parse_args()

    missing_uz = fill_locale("uz", 0)
    missing_ru = fill_locale("ru", 1)
    fill_locale("en", None)
    fill_cyrillic()

    missing = sorted(set(missing_uz) | set(missing_ru))
    for code in ("en", "uz", "uz_Cyrl", "ru"):
        catalogue = polib.pofile(str(LOCALE_DIR / code / "LC_MESSAGES" / "django.po"))
        total = len([e for e in catalogue if not e.obsolete])
        translated = len(catalogue.translated_entries())
        print(f"{code:<8} {translated}/{total} translated")

    if missing:
        print(f"\n{len(missing)} msgid(s) have no translation:")
        for msgid in missing:
            print(f"  {msgid!r}")
        if not args.list:
            print("\nAdd them to scripts/i18n_catalogue_*.py and run this script again.")
        return 1

    print("\nEvery message is translated in all four languages.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
