"""Uzbek (Latin) and Russian translations — part 7: the Stitch design refresh.

Strings introduced when the public site was rebuilt after ``design/``
(navy / gold "Academic Prestige" system): the utility bar, hero fact tiles,
discovery console, lead article card, issue sidebar, About page sections and
the dark footer.  Each entry maps an English ``msgid`` to
``(uzbek_latin, russian)``; Uzbek Cyrillic is generated by the transliterator.
"""

from __future__ import annotations

PART_7: dict[str, tuple[str, str]] = {
    # --- header / utility bar / footer ------------------------------------
    "Open access · double-blind peer review": (
        "Ochiq kirish · ikki tomonlama anonim taqriz",
        "Открытый доступ · двойное слепое рецензирование",
    ),
    "Editorial office": ("Tahririyat", "Редакция"),
    "Journal identifiers": ("Jurnal identifikatorlari", "Идентификаторы журнала"),
    "Sign in with Google": ("Google orqali kirish", "Войти через Google"),
    "Continue with Google": ("Google bilan davom etish", "Продолжить с Google"),
    "Continue with ORCID": ("ORCID bilan davom etish", "Продолжить с ORCID"),
    "Search articles, authors, JEL…": (
        "Maqola, muallif, JEL boʻyicha qidiring…",
        "Поиск по статьям, авторам, JEL…",
    ),
    "About & editorial": ("Jurnal va tahririyat", "О журнале и редакции"),
    "Peer review process": ("Taqriz jarayoni", "Процесс рецензирования"),
    "Open access statement": ("Ochiq kirish bayonoti", "Заявление об открытом доступе"),
    "Information": ("Maʼlumot", "Информация"),
    "Reviewer guidelines": ("Taqrizchilar uchun qoʻllanma", "Руководство для рецензентов"),
    "Archiving & indexing": ("Arxivlash va indekslash", "Архивирование и индексация"),
    "Indexing & abstracting": ("Indekslash va referatlash", "Индексация и реферирование"),
    # --- home: hero -------------------------------------------------------
    "Published by %(publisher)s": ("Muassis: %(publisher)s", "Издатель: %(publisher)s"),
    "Diamond open access · no APC": (
        "Olmos ochiq kirish · toʻlovsiz",
        "Бриллиантовый открытый доступ · без APC",
    ),
    "Publishing model": ("Nashr modeli", "Модель публикации"),
    "Diamond OA": ("Olmos OA", "Diamond OA"),
    "No author or reader fees": (
        "Muallif va oʻquvchi uchun toʻlov yoʻq",
        "Без платы для авторов и читателей",
    ),
    "Double-blind": ("Ikki tomonlama anonim", "Двойное слепое"),
    "Median %(days)s days to first decision": (
        "Birinchi qarorgacha median %(days)s kun",
        "Медиана %(days)s дней до первого решения",
    ),
    "Two independent reviewers": ("Ikki mustaqil taqrizchi", "Два независимых рецензента"),
    "Cadence": ("Davriylik", "Периодичность"),
    "plus Online First": ("va Online First", "плюс Online First"),
    "Languages": ("Tillar", "Языки"),
    "since %(year)s": ("%(year)s yildan beri", "с %(year)s года"),
    "Authors retain copyright": (
        "Mualliflik huquqi mualliflarda qoladi",
        "Авторские права остаются у авторов",
    ),
    # --- home: console ----------------------------------------------------
    "Search by title, author, DOI or JEL code (e.g. E52)": (
        "Sarlavha, muallif, DOI yoki JEL kodi boʻyicha qidiring (masalan, E52)",
        "Поиск по названию, автору, DOI или коду JEL (например, E52)",
    ),
    "All research": ("Barcha tadqiqotlar", "Все исследования"),
    # --- home: current issue and cards -----------------------------------
    "Latest release": ("Soʻnggi nashr", "Свежий выпуск"),
    "Full issue PDF": ("Toʻliq son (PDF)", "Весь выпуск (PDF)"),
    "Lead article": ("Bosh maqola", "Главная статья"),
    "pp.": ("b.", "с."),
    "Online": ("Onlayn", "Онлайн"),
    "Abstract & references": ("Annotatsiya va adabiyotlar", "Аннотация и литература"),
    "Showing %(shown)s of %(total)s articles in %(issue)s": (
        "%(issue)s sonidagi %(total)s maqoladan %(shown)s tasi koʻrsatilmoqda",
        "Показано %(shown)s из %(total)s статей выпуска %(issue)s",
    ),
    "View all papers in this issue": (
        "Ushbu sondagi barcha maqolalar",
        "Все статьи этого выпуска",
    ),
    # --- home: sidebar ----------------------------------------------------
    "Ahead of print": ("Nashrdan oldin", "До выхода номера"),
    "Peer-reviewed, accepted articles published immediately with a citable DOI.": (
        "Taqrizdan oʻtib qabul qilingan maqolalar iqtibos uchun DOI bilan darhol eʼlon qilinadi.",
        "Прошедшие рецензирование принятые статьи публикуются сразу с DOI для цитирования.",
    ),
    "View %(counter)s Online First article": (
        "%(counter)s ta Online First maqolani koʻrish",
        "Показать %(counter)s статью Online First",
    ),
    "View all %(counter)s Online First articles": (
        "Barcha %(counter)s ta Online First maqolani koʻrish",
        "Показать все %(counter)s статей Online First",
    ),
    "No articles are ahead of print at the moment.": (
        "Hozircha nashrdan oldingi maqolalar yoʻq.",
        "Сейчас нет статей до выхода номера.",
    ),
    "COPE-aligned": ("COPE tamoyillariga mos", "В соответствии с COPE"),
    "For researchers": ("Tadqiqotchilar uchun", "Для исследователей"),
    "Submission templates, the pre-submission checklist and the data policy, in one place.": (
        "Qoʻlyozma shablonlari, topshirishdan oldingi nazorat roʻyxati va maʼlumotlar siyosati — bir joyda.",
        "Шаблоны рукописи, контрольный список перед подачей и политика данных — в одном месте.",
    ),
    "Data & replication policy": (
        "Maʼlumotlar va replikatsiya siyosati",
        "Политика данных и репликации",
    ),
    "Call for papers": ("Maqolalar qabuli", "Приём статей"),
    # --- home: standards --------------------------------------------------
    "Research governance & rigour": (
        "Ilmiy boshqaruv va qatʼiylik",
        "Научное управление и строгость",
    ),
    "Publication standards & verification": (
        "Nashr standartlari va tekshiruv",
        "Стандарты публикации и проверка",
    ),
    "Every submission passes a multi-stage screening framework that protects academic integrity, empirical veracity and unbiased review.": (
        "Har bir qoʻlyozma ilmiy halollik, empirik ishonchlilik va xolis taqrizni taʼminlovchi koʻp bosqichli tekshiruvdan oʻtadi.",
        "Каждая рукопись проходит многоэтапную проверку, защищающую академическую честность, эмпирическую достоверность и непредвзятое рецензирование.",
    ),
    "Read the publication ethics statement": (
        "Nashr etikasi bayonotini oʻqish",
        "Читать заявление об этике публикаций",
    ),
    "Strict double-blind review": (
        "Qatʼiy ikki tomonlama anonim taqriz",
        "Строгое двойное слепое рецензирование",
    ),
    "Author and reviewer identities are concealed throughout. At least two independent external reports are required before any editorial decision.": (
        "Muallif va taqrizchi shaxsi butun jarayon davomida yashirin qoladi. Har qanday tahririyat qaroridan oldin kamida ikkita mustaqil tashqi taqriz talab etiladi.",
        "Личности авторов и рецензентов скрыты на протяжении всего процесса. До любого редакционного решения требуется не менее двух независимых внешних отзывов.",
    ),
    "Integrity screening": ("Halollik tekshiruvi", "Проверка добросовестности"),
    "Every manuscript is checked for similarity before review; reports above %(threshold)s%% are returned to the authors. Generative-AI use must be disclosed.": (
        "Har bir qoʻlyozma taqrizdan oldin oʻxshashlikka tekshiriladi; %(threshold)s%% dan yuqori hisobotlar mualliflarga qaytariladi. Generativ AI dan foydalanish oshkor qilinishi shart.",
        "Каждая рукопись проверяется на заимствования до рецензирования; отчёты выше %(threshold)s%% возвращаются авторам. Использование генеративного ИИ должно быть раскрыто.",
    ),
    "Diamond open access charter": (
        "Olmos ochiq kirish xartiyasi",
        "Хартия бриллиантового открытого доступа",
    ),
    "All articles are freely accessible worldwide on the day of publication under CC BY 4.0. No article processing charges are levied on authors or their institutions.": (
        "Barcha maqolalar nashr kunidan boshlab CC BY 4.0 litsenziyasi ostida butun dunyoda bepul ochiq. Mualliflar va ularning muassasalaridan hech qanday toʻlov olinmaydi.",
        "Все статьи свободно доступны во всём мире со дня публикации по лицензии CC BY 4.0. Плата за обработку статей с авторов и их организаций не взимается.",
    ),
    "Abstracting, indexing & archival repositories": (
        "Referatlash, indekslash va arxiv omborlari",
        "Реферирование, индексация и архивные репозитории",
    ),
    # --- issue page -------------------------------------------------------
    "Published issue": ("Nashr etilgan son", "Опубликованный выпуск"),
    "%(counter)s peer-reviewed paper": (
        "%(counter)s ta taqrizdan oʻtgan maqola",
        "%(counter)s рецензируемая статья",
    ),
    "%(counter)s peer-reviewed papers": (
        "%(counter)s ta taqrizdan oʻtgan maqola",
        "%(counter)s рецензируемых статей",
    ),
    "Issue sequence": ("Sonlar ketma-ketligi", "Последовательность выпусков"),
    "First issue": ("Birinchi son", "Первый выпуск"),
    "Latest issue": ("Soʻnggi son", "Последний выпуск"),
    "Issues in this volume": ("Ushbu jilddagi sonlar", "Выпуски этого тома"),
    "All volumes": ("Barcha jildlar", "Все тома"),
    "Issue metrics & indexing": (
        "Son koʻrsatkichlari va indekslash",
        "Метрики выпуска и индексация",
    ),
    "Abstract page views": ("Annotatsiya sahifasi koʻrishlari", "Просмотры страниц аннотаций"),
    "PDF downloads": ("PDF yuklab olishlar", "Загрузки PDF"),
    "Open access licence": ("Ochiq kirish litsenziyasi", "Лицензия открытого доступа"),
    "Machine-readable": ("Mashina oʻqiy oladigan", "Машиночитаемый формат"),
    "Read the announcement": ("Eʼlonni oʻqish", "Читать объявление"),
    # --- page shell -------------------------------------------------------
    "Author submission kit": ("Muallif toʻplami", "Набор автора"),
    "Download the manuscript template and the pre-submission checklist before you submit.": (
        "Topshirishdan oldin qoʻlyozma shablonini va nazorat roʻyxatini yuklab oling.",
        "Перед подачей скачайте шаблон рукописи и контрольный список.",
    ),
    "Template": ("Shablon", "Шаблон"),
    # --- about page -------------------------------------------------------
    "Diamond open access": ("Olmos ochiq kirish", "Бриллиантовый открытый доступ"),
    "COPE-aligned ethics": ("COPE ga mos etika", "Этика в соответствии с COPE"),
    "Institutional profile": ("Institutsional profil", "Институциональный профиль"),
    "Model": ("Model", "Модель"),
    "Review model": ("Taqriz modeli", "Модель рецензирования"),
    "Min. 2 external reviewers": ("Kamida 2 tashqi taqrizchi", "Мин. 2 внешних рецензента"),
    "First decision": ("Birinchi qaror", "Первое решение"),
    "%(days)s days": ("%(days)s kun", "%(days)s дней"),
    "median, last 12 months": ("median, soʻnggi 12 oy", "медиана, последние 12 месяцев"),
    "What we publish": ("Nimalarni nashr etamiz", "Что мы публикуем"),
    "Methodologically sound empirical and theoretical scholarship relevant to emerging markets and transition economies.": (
        "Rivojlanayotgan bozorlar va oʻtish iqtisodiyotlariga oid metodologik jihatdan asosli empirik va nazariy tadqiqotlar.",
        "Методологически обоснованные эмпирические и теоретические исследования, значимые для развивающихся рынков и переходных экономик.",
    ),
    "Need detailed guidance for your research domain?": (
        "Tadqiqot yoʻnalishingiz boʻyicha batafsil yoʻriqnoma kerakmi?",
        "Нужны подробные указания по вашей области исследований?",
    ),
    "Explore the full aims & scope": (
        "Toʻliq maqsad va koʻlamni koʻring",
        "Полные цели и тематика",
    ),
    "How we work": ("Biz qanday ishlaymiz", "Как мы работаем"),
    "A transparent five-stage editorial system that follows the Committee on Publication Ethics (COPE) core practices.": (
        "Nashr etikasi qoʻmitasi (COPE) asosiy amaliyotlariga tayanadigan shaffof besh bosqichli tahririyat tizimi.",
        "Прозрачная пятиэтапная редакционная система, следующая основным практикам Комитета по этике публикаций (COPE).",
    ),
    "Desk screening & similarity check": (
        "Dastlabki koʻrik va oʻxshashlik tekshiruvi",
        "Первичная проверка и проверка на заимствования",
    ),
    "within days of receipt": (
        "kelib tushgandan keyin bir necha kun ichida",
        "в течение нескольких дней после получения",
    ),
    "Every manuscript is screened for scope, anonymisation and similarity; reports above %(threshold)s%% go back to the authors before review.": (
        "Har bir qoʻlyozma koʻlam, anonimlik va oʻxshashlik boʻyicha tekshiriladi; %(threshold)s%% dan yuqori hisobotlar taqrizdan oldin mualliflarga qaytariladi.",
        "Каждая рукопись проверяется на соответствие тематике, анонимность и заимствования; отчёты выше %(threshold)s%% возвращаются авторам до рецензирования.",
    ),
    "at least two reviewers": ("kamida ikki taqrizchi", "не менее двух рецензентов"),
    "A handling editor invites independent reviewers; author and reviewer identities stay hidden from each other throughout.": (
        "Masʼul muharrir mustaqil taqrizchilarni taklif qiladi; muallif va taqrizchi shaxsi butun jarayon davomida bir-biridan yashirin qoladi.",
        "Ответственный редактор приглашает независимых рецензентов; личности автора и рецензента скрыты друг от друга на протяжении всего процесса.",
    ),
    "Editorial decision & revision rounds": (
        "Tahririyat qarori va qayta ishlash bosqichlari",
        "Редакционное решение и раунды доработки",
    ),
    "reasoned reports": ("asoslangan hisobotlar", "мотивированные отзывы"),
    "Accept, minor revision, major revision or reject — always with the reviewers' reports and the editor's reasoning.": (
        "Qabul, kichik yoki katta qayta ishlash yoki rad etish — har doim taqrizchilar hisobotlari va muharrir asoslari bilan.",
        "Принять, небольшая или существенная доработка либо отклонить — всегда с отзывами рецензентов и обоснованием редактора.",
    ),
    "Copyediting, typesetting & DOI registration": (
        "Tahrir, sahifalash va DOI roʻyxatga olish",
        "Литературная правка, вёрстка и регистрация DOI",
    ),
    "Crossref": ("Crossref", "Crossref"),
    "Accepted manuscripts are copyedited, typeset, checked by the authors and registered with a DOI and full reference list.": (
        "Qabul qilingan qoʻlyozmalar tahrir qilinadi, sahifalanadi, mualliflar tomonidan tekshiriladi hamda DOI va toʻliq adabiyotlar roʻyxati bilan roʻyxatga olinadi.",
        "Принятые рукописи проходят правку, вёрстку, авторскую проверку и регистрируются с DOI и полным списком литературы.",
    ),
    "Online First & issue publication": (
        "Online First va sonda nashr",
        "Online First и публикация в выпуске",
    ),
    "immediate open access": ("darhol ochiq kirish", "немедленный открытый доступ"),
    "Articles appear ahead of print as soon as production is complete and are assigned to the next issue.": (
        "Maqolalar ishlab chiqarish tugashi bilan nashrdan oldin eʼlon qilinadi va navbatdagi songa biriktiriladi.",
        "Статьи появляются до выхода номера сразу после завершения подготовки и включаются в следующий выпуск.",
    ),
    "Publication ethics": ("Nashr etikasi", "Этика публикаций"),
    "COPE core practices, retraction policy and generative-AI disclosure.": (
        "COPE asosiy amaliyotlari, qaytarib olish siyosati va generativ AI ni oshkor qilish.",
        "Основные практики COPE, политика отзыва статей и раскрытие использования генеративного ИИ.",
    ),
    "Read the ethics charter": ("Etika xartiyasini oʻqish", "Читать хартию этики"),
    "Editorial leadership": ("Tahririyat rahbariyati", "Редакционное руководство"),
    "Guided by scholars from universities, central banks and research institutes.": (
        "Universitetlar, markaziy banklar va tadqiqot institutlari olimlari rahbarligida.",
        "Под руководством учёных из университетов, центральных банков и научных институтов.",
    ),
    "Full editorial board": ("Toʻliq tahririyat kengashi", "Полный состав редколлегии"),
    "DEMO — replace": ("DEMO — almashtiring", "DEMO — заменить"),
    "%(counter)s board member": ("%(counter)s kengash aʼzosi", "%(counter)s член редколлегии"),
    "%(counter)s board members": ("%(counter)s kengash aʼzosi", "%(counter)s членов редколлегии"),
    "Abstracting, indexing & archiving": (
        "Referatlash, indekslash va arxivlash",
        "Реферирование, индексация и архивирование",
    ),
    "Articles are permanently identified, archived and deposited across scholarly record repositories.": (
        "Maqolalar doimiy identifikatorga ega, arxivlanadi va ilmiy omborlarga joylashtiriladi.",
        "Статьи получают постоянные идентификаторы, архивируются и депонируются в репозиториях научных записей.",
    ),
    "Editorial secretariat": ("Tahririyat kotibiyati", "Редакционный секретариат"),
    "Have questions about your submission?": (
        "Qoʻlyozmangiz boʻyicha savollaringiz bormi?",
        "Есть вопросы по вашей рукописи?",
    ),
    "The editorial office offers pre-submission consultation on scope, special issue proposals and institutional partnerships.": (
        "Tahririyat koʻlam, maxsus son takliflari va institutsional hamkorlik boʻyicha topshirishdan oldingi maslahat beradi.",
        "Редакция консультирует до подачи по тематике, предложениям специальных выпусков и институциональному партнёрству.",
    ),
}
