"""Deterministic Uzbek Latin ↔ Cyrillic transliteration.

The journal publishes in four locales, two of which are the same language in
two scripts (``uz`` Latin and ``uz-cyrl`` Cyrillic).  Editors write Latin text;
the Cyrillic variant is machine generated by :func:`to_cyrillic` and may then be
corrected by hand.

Rules implemented (Oʻzbek lotin yozuvi, 1995 alphabet):

* digraphs ``sh ch ng ts yo yu ya ye`` are matched before single letters;
* ``oʻ`` and ``gʻ`` accept every apostrophe variant (``ʻ ʼ ' ` ‘ ’``);
* word-initial ``e`` becomes ``э``, elsewhere ``е``;
* word-initial ``ye`` becomes ``е``;
* the tutuq belgisi ``ʼ`` becomes ``ъ``;
* capitalisation of the source token is preserved (Title Case and ALL CAPS);
* a small exception dictionary handles loanwords whose accepted Cyrillic
  spelling does not follow the letter-by-letter rules.
"""

from __future__ import annotations

import re

__all__ = ["APOSTROPHES", "EXCEPTIONS_LAT_CYR", "to_cyrillic", "to_latin"]

#: Every character that may be used as the Uzbek modifier apostrophe.
APOSTROPHES = "ʻʼ'`‘’´"

_APOSTROPHE_CLASS = f"[{re.escape(APOSTROPHES)}]"

#: Loanwords and proper nouns whose Cyrillic spelling is fixed by convention.
EXCEPTIONS_LAT_CYR: dict[str, str] = {
    "algoritm": "алгоритм",
    "arxiv": "архив",
    "avgust": "август",
    "byudjet": "бюджет",
    "dotsent": "доцент",
    "ekonometrika": "эконометрика",
    "ekspert": "эксперт",
    "ekspertiza": "экспертиза",
    "elektron": "электрон",
    "email": "e-mail",
    "iqtisodiyot": "иқтисодиёт",
    "internet": "интернет",
    "jurnal": "журнал",
    "konferensiya": "конференция",
    "litsenziya": "лицензия",
    "maqola": "мақола",
    "oktyabr": "октябрь",
    "professor": "профессор",
    "publikatsiya": "публикация",
    "redaksiya": "редакция",
    "sentyabr": "сентябрь",
    "statistika": "статистика",
    "tsivilizatsiya": "цивилизация",
    "universitet": "университет",
}

EXCEPTIONS_CYR_LAT: dict[str, str] = {
    cyr: lat for lat, cyr in EXCEPTIONS_LAT_CYR.items() if cyr.isalpha()
}

# Ordered longest-first so that digraphs win over single letters.
_LAT_TO_CYR: tuple[tuple[str, str], ...] = (
    ("yo", "ё"),
    ("yu", "ю"),
    ("ya", "я"),
    ("ch", "ч"),
    ("sh", "ш"),
    ("ts", "ц"),
    ("oʻ", "ў"),
    ("gʻ", "ғ"),
    ("a", "а"),
    ("b", "б"),
    ("d", "д"),
    ("e", "е"),
    ("f", "ф"),
    ("g", "г"),
    ("h", "ҳ"),
    ("i", "и"),
    ("j", "ж"),
    ("k", "к"),
    ("l", "л"),
    ("m", "м"),
    ("n", "н"),
    ("o", "о"),
    ("p", "п"),
    ("q", "қ"),
    ("r", "р"),
    ("s", "с"),
    ("t", "т"),
    ("u", "у"),
    ("v", "в"),
    ("x", "х"),
    ("y", "й"),
    ("z", "з"),
    ("c", "к"),
    ("w", "в"),
)

_CYR_TO_LAT: tuple[tuple[str, str], ...] = (
    ("ё", "yo"),
    ("ю", "yu"),
    ("я", "ya"),
    ("ч", "ch"),
    ("ш", "sh"),
    ("ц", "ts"),
    ("щ", "shch"),
    ("ў", "oʻ"),
    ("ғ", "gʻ"),
    ("а", "a"),
    ("б", "b"),
    ("в", "v"),
    ("г", "g"),
    ("д", "d"),
    ("е", "e"),
    ("ж", "j"),
    ("з", "z"),
    ("и", "i"),
    ("й", "y"),
    ("к", "k"),
    ("қ", "q"),
    ("л", "l"),
    ("м", "m"),
    ("н", "n"),
    ("о", "o"),
    ("п", "p"),
    ("р", "r"),
    ("с", "s"),
    ("т", "t"),
    ("у", "u"),
    ("ф", "f"),
    ("х", "x"),
    ("ҳ", "h"),
    ("ъ", "ʼ"),
    ("ь", ""),
    ("э", "e"),
    ("ы", "i"),
)

_LATIN_WORD_RE = re.compile(rf"[A-Za-z{re.escape(APOSTROPHES)}]+")
_CYRILLIC_WORD_RE = re.compile(r"[А-Яа-яЁёЎўҚқҒғҲҳ]+")


def _normalise_apostrophes(text: str) -> str:
    """Collapse every apostrophe variant to ``ʻ`` (U+02BB)."""
    return re.sub(_APOSTROPHE_CLASS, "ʻ", text)


def _restore_case(source: str, converted: str) -> str:
    """Apply the capitalisation pattern of ``source`` to ``converted``."""
    letters = [c for c in source if c.isalpha()]
    if not letters:
        return converted
    if len(letters) > 1 and all(c.isupper() for c in letters):
        return converted.upper()
    if letters[0].isupper():
        return converted[:1].upper() + converted[1:]
    return converted


def _convert_latin_word(word: str) -> str:
    """Transliterate a single Latin word to Cyrillic."""
    lowered = _normalise_apostrophes(word).lower()
    exception = EXCEPTIONS_LAT_CYR.get(lowered.strip("ʻ"))
    if exception is not None:
        return _restore_case(word, exception)

    out: list[str] = []
    i = 0
    n = len(lowered)
    while i < n:
        # Word-initial special cases for the letter "e".
        if i == 0 and lowered.startswith("ye"):
            out.append("е")
            i += 2
            continue
        if i == 0 and lowered[0] == "e":
            out.append("э")
            i += 1
            continue
        # "yoʻ" is y + oʻ (йў), not the digraph "yo" followed by an apostrophe.
        if lowered.startswith("yoʻ", i):
            out.append("йў")
            i += 3
            continue
        if lowered.startswith("ygʻ", i):
            out.append("йғ")
            i += 3
            continue
        if lowered[i] == "ʻ":
            # A standalone apostrophe is the tutuq belgisi.
            out.append("ъ")
            i += 1
            continue
        for src, dst in _LAT_TO_CYR:
            if lowered.startswith(src, i):
                out.append(dst)
                i += len(src)
                break
        else:  # pragma: no cover - defensive
            out.append(lowered[i])
            i += 1
    return _restore_case(word, "".join(out))


def _convert_cyrillic_word(word: str) -> str:
    """Transliterate a single Cyrillic word to Latin."""
    lowered = word.lower()
    exception = EXCEPTIONS_CYR_LAT.get(lowered)
    if exception is not None:
        return _restore_case(word, exception)

    out: list[str] = []
    i = 0
    n = len(lowered)
    while i < n:
        if i == 0 and lowered[0] == "е":
            out.append("ye")
            i += 1
            continue
        for src, dst in _CYR_TO_LAT:
            if lowered.startswith(src, i):
                out.append(dst)
                i += len(src)
                break
        else:  # pragma: no cover - defensive
            out.append(lowered[i])
            i += 1
    return _restore_case(word, "".join(out))


def to_cyrillic(text: str | None) -> str:
    """Transliterate Uzbek Latin ``text`` into the Cyrillic script.

    Non-Uzbek characters (digits, punctuation, HTML tags, URLs) pass through
    unchanged, so the function is safe to apply to short rich-text fields.
    """
    if not text:
        return ""
    return _LATIN_WORD_RE.sub(lambda m: _convert_latin_word(m.group(0)), text)


def to_latin(text: str | None) -> str:
    """Transliterate Uzbek Cyrillic ``text`` into the Latin script."""
    if not text:
        return ""
    return _CYRILLIC_WORD_RE.sub(lambda m: _convert_cyrillic_word(m.group(0)), text)
