# Generated by Django 5.2.17 on 2026-09-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doi_batch_id', models.CharField(max_length=64, unique=True, verbose_name='batch ID')),
                ('xml', models.FileField(blank=True, null=True, upload_to='crossref/', verbose_name='deposit XML')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16, verbose_name='status')),
                ('response_log', models.TextField(blank=True, verbose_name='response log')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('is_test', models.BooleanField(default=True, verbose_name='test deposit')),
                ('is_update', models.BooleanField(default=False, verbose_name='metadata update')),
            ],
            options={
                'verbose_name': 'deposit batch',
                'verbose_name_plural': 'deposit batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DOIRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('doi', models.CharField(max_length=128, verbose_name='DOI')),
                ('status', models.CharField(default='pending', max_length=32, verbose_name='status')),
                ('message', models.TextField(blank=True, verbose_name='message')),
            ],
            options={
                'verbose_name': 'DOI registration',
                'verbose_name_plural': 'DOI registrations',
                'ordering': ['-created_at'],
            },
        ),
    ]
