# Generated by Django 5.2.17 on 2026-09-04 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crossref', '0001_initial'),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositbatch',
            name='articles',
            field=models.ManyToManyField(blank=True, related_name='deposit_batches', to='journal.article', verbose_name='articles'),
        ),
        migrations.AddField(
            model_name='doiregistration',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doi_registrations', to='journal.article', verbose_name='article'),
        ),
        migrations.AddField(
            model_name='doiregistration',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='crossref.depositbatch', verbose_name='batch'),
        ),
        migrations.AddIndex(
            model_name='depositbatch',
            index=models.Index(fields=['status', '-created_at'], name='crossref_de_status_941185_idx'),
        ),
    ]
